### ISSUE TITLE
Remove emphasis/detail regarding 2010 cohort from document/presentations

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1038]
For the 2024 assessment the emphasis on the 2010 cohort should be decreased given that they are over a decade old.

From Trevor's comments in #1031 
- [ ] p. 60-61 perhaps a good time to delete the highly detailed account of the 2010 year class since this no longer contributes to the fishery very much. Similarly for the detailed examination of the 2010 vs. 2014 recruitment comparison, which now seems dated.
- [x] Table 33-35 Here the size of the 2020 recruitment should be added and the 2010 recruitment deleted. 
- [x] Figure 31 seems superfluous and can be deleted (R/R2010).

**Comment by andrew-edwards** [comment]
There's actually a few different ideas here getting slightly mixed up. Based on the above tickboxes:
1. Text at bottom of page 60 (last year's assessment) - I think he's referring to "The very strong 2010 year class comprised 64% of the coast-wide commercial catch in 2014...." and other catch years. Agree that can go (as not likely to change from assessment to assessment anyway), and it's already been deleted.
The 'detailed examination of 2010 v 2014' is the paragraph on my scaled recruitment figure, for which the point is understanding relative strengths (not caring about 2010 v 2014 per se), so I can clarify that up front. See discussion on 26b393d.
2. Table 33-35: 2020 recruitment was already in those tables. So 2010 could be deleted because it's somewhat old, but also could certainly be kept in as it's (almost certainly) the largest since 1980 and so is a valuable reference. I think it might be valuable to keep in (although values are in other tables, so not essential).
3. See discussion on 26b393d. I think Trevor missed the presentation a couple of years back about the motivation for the figure. I can certainly change the text though.  
Sorry, I hadn't got to thinking about these issues yet.
