### ISSUE TITLE
Lack of input uncertainty for survey data

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#1075]
https://github.com/pacific-hake/hake-assessment/blob/dd81068b3b34980e6b48c307a322a513ace2f29a/R/plot-survey-fit-mcmc.R#L69
The previous function does not include any measurement of uncertainty for the input time series of CPUE that can be found in the data file. For both surveys we have the input values (given to us by FEAT) and we have additional estimates of variability that are estimated within the SS3 model. It would be nice to know if the estimates of from the time series and their confidence intervals fall within the input/additional uncertainty of the "data".

**Comment by cgrandin** [comment]
That is shown with the thick lines. I had to fix the legend though, so you can read it (36f3f9263b8000b997e196a32f3f1aaedc99cf11)

For the survey:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/cd989f5a-8fc3-4f13-85d3-05937970b13b)

For the age-1 index:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/47963048-dfd1-4483-b246-ff3e176ddf85)

**Comment by cgrandin** [comment]
Looking at the whole age-1 plot, not zoomed-in:
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/154ab7bf-2b2f-438b-b36c-09e68808d80b)
I'll change this in the doc so it shows the latter

**Comment by kellijohnson-NOAA** [comment]
I cannot see the difference between thick and thin in the black vertical lines.

**Comment by cgrandin** [comment]
Well they were blue, how about now?
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/e6cdb30e-46c4-441c-93b3-f8322891cd8f)

**Comment by kellijohnson-NOAA** [comment]
Thanks Chris that is a lot easier to see. One other thing that might need some tweaking is the text in the legend. It is unclear to me  what "estimated (thin) 95% intervals" actually means. Is that the estimated 95% confidence interval based on the median MCMC estimate of the additional variance plus the input uncertainty? @aaronmberger-nwfsc do you have any suggestions for wording here?

**Comment by aaronmberger-nwfsc** [comment]
The figure looks great, and I really like the detail.  Let's just keep in the back of our mind to check to ensure this detail isn't degraded during the process where the NOAA West Coast region takes our final document and then posts it online (e.g., no degradation in quality like has happened before). This goes for many of our new figures I think.

In terms of the legend, I see your point Kelli.  What we are showing is the point estimate (black dot) and standard deviation (black thick line) for the survey age-1 index estimate itself - though in our assessment model context those things are 'data' (i.e., input values).  The additional standard deviation (black thin line) is indeed an assessment model estimate, so that would be the median MCMC estimate of an additional standard deviation parameter. I don't think we are showing anything to do with 95% credible interval at all in this figure, even though it intuitively looks like it. 

All this (and even more details below) to suggest that perhaps we say:
In the legend for the top entry - "Observed age-1 index with input (thick) and additional estimated (median MCMC; thin) standard deviation"
In the caption - "Assessment model fit to the relative age-1 index data that was produced from acoustic survey observations. 
Age-1 index observations (black dots) are input into the assessment model with uncertainty arising from sampling variability (thick vertical black lines).  Additional uncertainty is estimated within the stock assessment model (thin vertical black lines) and added to the input sampling variability. A time series of the assessment model fit to the observations (blue line) represents the median of the posterior MCMC samples. A random subset of the individual MCMC time series samples are shown (thin black lines) to provide context for the description of the median MCMC estimate."

Or something like that.  And I note that currently our 'sampling variability' is assumed to be 0.5; it's not actually measured (yet, see below).

Some further details, which I don't think need to go into the legend or caption, but could be good to think about if the age-1 index section of text in the main document is not clear.
The input age-1 index standard deviation is entered as 'data' (or sampling variability data) with an interpretation as a coefficient of variation (or similarly log standard deviation) and currently is 'assumed' by us to be equal to 0.5. Thus, in the figure we see the uncertainty range (length of thick line) change on the normal scale by year shown here because it is input as a constant on a log scale (so multiplicative effect on the normal scale).  The survey team has on their task list to produce actual input CV's (or log SD's) for us so we don't need to assume a value.

The assessment estimated additional standard deviation is indeed an MCMC estimate, so my understanding is that we are showing here the median estimate.  The additional standard deviation estimate is a single value (estimated on the log scale) across all years, so again we see the uncertainty range (length of thin line) change on the normal scale by year in the same way as described earlier.

**Comment by aaronmberger-nwfsc** [comment]
I think we can close with 8467028bbc444645225c92c312f2bfdeffacc428
