### ISSUE TITLE
Update oceanographic conditions regarding age-1 index in 3.4.2 Model Fit subsection 

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1102]
We had a nice paragraph for 2021 age-1 index (kept in for now with a TODO and mention of this issue). Needs updating, with updated California Current Ecosystem Status Report if available (looks like it's produced annually like GOA one is). I can look into unless someone already knows the Status Report well.

**Comment by andrew-edwards** [comment]
https://www.pcouncil.org/documents/2023/02/h-1-a-cciea-team-report-1-electronic-only-2022-2023-california-current-ecosystem-status-report-and-appendices.pdf/

https://www.youtube.com/watch?v=tJUhi-NT3sI

**Comment by aaronmberger-nwfsc** [comment]
We could probably get a draft of the 2023-2024 CCIEA report as it is due about the same time as our assessment.  It would be citable in by the time we finalize the assessment document.

**Comment by aaronmberger-nwfsc** [comment]
Some highlights from the draft 2023-2024 CCIEA report (in prep):
- "Basin-scale indices suggest average conditions for productivity in 2023: the ONI and PDO were negative for most of the year, while the NPGO remained neutral to negative."
- "In contrast, hake larvae were above average for the second consecutive year and at their highest abundance since 2011." - from CalCOFI survey in southern California current area
- "Consumption of hake was well above average for bluefin and swordfish in both 2021 and 2022."
- "Overall, 2023 saw lower total integrated upwelling compared to previous years (Fig. F.8), except for the most southern region. However, upwelling events were highly variable in strength and timing, consisting of periods of strong upwelling, interspersed with several periods of significant upwelling relaxation, or even downwelling (Fig. 2.4)."  - weaker upwelling was associated with positive hake recruitment from Vestfals paper.
- "Total krill abundances in 2023 were the second lowest since the start of the time series in 2007, although most of that overall reduction was due to lower numbers to the northern and southern portions of the sampled area. "

**Comment by aaronmberger-nwfsc** [comment]
I'm thinking that this paragraph in the assessment should be moved to the Ecosystem Considerations section and removed from section 3.4.2.  If needed, this Model Fit section could reference the Ecosystem Considerations section.

**Comment by aaronmberger-nwfsc** [comment]
completed with aa939756ffcffedac5cd3c50470f10d1e5c7ee0a
