### ISSUE TITLE
base_model$mcmcvals$dm_weight_survey_median is incorrect

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1117]
The value loaded into mcmcvals for the dm_weight_survey_median is incorrect.  It currently is loaded with the value for dm_weight_fishery_median.  These are used in the sensitivity section to auto-populated the correct values.  I've updated the text to be correct once the this is fixed.

I tracked the issue back to load-mcmc-vals.R, but have stopped there.

**Comment by cgrandin** [comment]
Currently, Dirichlet-multinomial fishery is set to `ln(DM_theta)_Age_P1`
and Dirichlet-multinomial survey is set to `ln(DM_theta)_Age_P2` here:

Run this to see:
```
get_col_name_from_key_title(`
    base_model$mcmc,
    pat = "Dirichlet-multinomial survey")
```

> [1] "ln(DM_theta)_Age_P2"

So that seems right? 

`dm_weight_survey_median` is being set to those values here: https://github.com/pacific-hake/hake-assessment/blob/eec374079395c0d441fe9e8b6fdd49d45e2c6fc6/doc/004-load-project-variables.rmd#L952

What about it makes it appear incorrect?

**Comment by cgrandin** [comment]
`dm_weight_survey_median` is equal to `dm_weight_fishery_median`.; Kelli found a bug where they ended up being equal and fixed it, but I don not remember if we re-ran the base model RDS building step after that.

So you're probably right

**Comment by cgrandin** [comment]
Does this make more sense

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/6f121e87-dfb6-49c2-a673-0a96b9ad277f)

**Comment by cgrandin** [comment]
It's fixed. You need to re-download the base model. Once loaded you can check this by looking at 
```
base_model$mcmcvals$dm_weight_survey_median
```

Kelli fixed the bug awhile ago but the routine to build the RDS file hadn't been run again since so it remained the same as the value in `base_model$mcmcvals$dm_weight_fishery_median`

**Comment by aaronmberger-nwfsc** [comment]
Yes, those numbers match my hand calculations, so all good.
