### ISSUE TITLE
Cosmetic - Swap order of ovary table and fecundity table (14 and 15)

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1120]
Can we swap order of ovary table (14) and fecundity table (15) so that the fecundity table does not split leaving 1 line alone on the next page? The other option is reduce the font size of the fecundity table but then it will be smaller than the other tables around it.

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/453963ec-5b35-4d09-a5b5-f0114580df22)

**Comment by kellijohnson-NOAA** [comment]
I kind of think that we can remove Table 14 because we have tv maturity which is not captured in this table.

**Comment by cgrandin** [comment]
That would fix the cosmetic issue as well. If there are no objections, I'll do that

**Comment by cgrandin** [comment]
Does that mean remove this figure as well?
![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/bd9217f6-33da-477d-ac86-36781aa4e1b9)

There is a TODO right where these are referenced.. here:
https://github.com/pacific-hake/hake-assessment/blob/e6fbce23e41ac5de3e7ad90a5f99ee3df8497249/doc/008-data.rmd#L48

So that part would have to be re-written/removed but I wasn't sure exactly what you were going to do there @kellijohnson-NOAA

**Comment by kellijohnson-NOAA** [comment]
I made a few preliminary figures for the maturity at age. The first, is the difference between the ogive we have been using, the same analysis but done without Canadian data, and Eric's NULL model that does not have time or space (i.e., basically trying to replicate Melissa Head's work). I am not sure if this needs to go in the document or just in our presentation. The second figure is of time-varying maturity-at-age but I decided to use lines instead of ridges or coloured tiles. 
1. 
![diff-ogives](https://github.com/pacific-hake/hake-assessment/assets/4108564/d1f8bbf3-dc7e-4a9e-ae7e-54d72409fb84)
2. 
![annual-ogives](https://github.com/pacific-hake/hake-assessment/assets/4108564/181bb5ce-a8bf-46d0-b4c4-c1d97bdf401d)
As always, all comments are welcome. Though, I do know that I cut off the labels when I saved them but I am too lazy to fix it right now. FYI these data are in the package in `maturity_estimates_df` if you want to play around with them.

**Comment by aaronmberger-nwfsc** [comment]
My thoughts:

For the document: I'm thinking that we need to show the time-varying maturity figure (your 2nd figure Kelli) because that is what is being used in the base assessment model, but I think we need to add what is being used during the historical period (pre-2009; unless that is what the 2009 line itself represents).  That way we show a complete time series picture.  If we then replace our old 'North'/'South' maturity figure we then lose sample sizes, but if we keep the sample size table then we are still covered at least in terms of total samples, we still won't show samples by year but that will be in the appendix (correct Kelli?).  In fact, this new analysis is using many more samples than the maturity analysis used in previous assessments (and thus shown as sample sizes in that north/south figure).

For the SRG presentation: I think we can show the figure in the document (suggestion above) and also your first figure Kelli, with the null model, and maybe add again there our previously used ogive for comparison. As a reminder, Canada data was too sparse for t.v. maturity, but it was not for stationary maturity, correct? (i.e., that's why the first figure includes adding Canada).

**Comment by andrew-edwards** [comment]
Agree with Aaron. New one certainly shows the changes at age-3 nicely. (Presume tick marks can get added, little hard to hone in on age-3 without them). Thanks for doing this.

**Comment by kellijohnson-NOAA** [comment]
@aaronmberger-nwfsc great comment about equilibrium maturity, I am assuming this comment also pertains to forecasted years as well. I can add those lines. Then regarding the sample sizes, they are all in the appendix. But, I think we should still remove Table 14 and change the sample sizes in Table 15 to be what was used not everything that was collected because some of those do not have functional maturity and thus cannot be used for any analysis.

**Comment by kellijohnson-NOAA** [comment]
Fixed the tables and now, I am working on the figures
![image](https://github.com/pacific-hake/hake-assessment/assets/4108564/a89a382a-8bc4-4d0e-8c81-21659b6fd12c)

**Comment by kellijohnson-NOAA** [comment]
Thanks to @cgrandin this is done. Sorry the code that I pushed last night was such a mess. And, thanks for iteratively working with me to get something that readers will actually be able to see the differences in the ogives. Way to go @cgrandin 🥇 .
