### ISSUE TITLE
Question - Should we make at-age tables in kilotonnes instead of tonnes?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#1121]
Tables "Estimated catch-at-age in numbers" (21) and
"Estimated catch-at-age in total biomass" (22) could shown in kt instead.

If so they will:
- match table "Estimated total biomass-at-age" (19) which is already in kt
- be able to have larger font (if sigfigs reduced) so easier to read

**Comment by andrew-edwards** [comment]
Didn't we truncate these at 15+ in the past? That would help the font problem. In Table 20 all the number are the same anyway for ages 15-20, and we have a 15+ age class.

Anyhow, I'd say leave Table 22 as is (catch-at-age) because there will be lots <1kt, and thinking about 0.5 kt requires a bit of mental juggling.

Table 21 is numbers of fish (not mass), and already in thousands. So also good as is I reckon.

**Comment by cgrandin** [comment]
Right, the numbers table. We could do millions of fish though. Reporting to 5 sigfigs is probably wrong for numbers.

..And biomass. So 500t would become 1kt and 499t would become 0 kt.
I'll wait to hear from others before closing

**Comment by aaronmberger-nwfsc** [comment]
I guess I'd vote for leaving those as a bit more detailed as that is where people go to look at details.  Speaking of details, do the out-csv files get automatically updated (i.e., so they are ready to send out too on Friday)?

**Comment by cgrandin** [comment]
@aaronmberger-nwfsc Yes those files get created and they're correct.

**Comment by cgrandin** [comment]
Just leaving it for this year then. Close
