### ISSUE TITLE
Consider adding distribution of catchability figure to assessment document

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1125]
Per internal reviewer suggestion: given there is text in the description of base model saying 'distribution of catchability', perhaps we should add that figure we already make for presentations to the main document. 

This can be done after the SRG draft is sent off.

**Comment by cgrandin** [comment]
I added this to the doc, but didn't close it because I ran out of time to 
make sure there are references to it in the text, etc.
I put it immediately following the catch density plot but feel free to move it.

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/26d09f95-a884-4d00-b982-91a7a78c0ee0)

**Comment by aaronmberger-nwfsc** [comment]
Chris has fixed this and we should be able to close this issue after we make sure everyone has downloaded the updated 01-base.rds file.
 - [ ] Chris
 - [ ] Aaron
 - [ ] Kelli
 - [ ] Andy

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards you will have to update the base model rds file once you are back!
