### ISSUE TITLE
survey fits in bridging figures don't seem to line up

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#1138]
I can't seem to understand the survey biomass fit plots in the bridging figures.  The green line (base model) in bridging set 2 stock biomass doesn't go up until 2024 (2022 to 2023 is nearly stable; ~slight decline), but in the survey biomass fit it goes way up in 2023 (seems like it should be 2024).  I'm wondering if there is a year error here?

![image](https://github.com/pacific-hake/hake-assessment/assets/7946234/0c5d8747-c644-4e47-a690-aca78300c7bb)

![image](https://github.com/pacific-hake/hake-assessment/assets/7946234/59fbb53a-ee20-4f6d-946b-938fc0ac9d3e)

**Comment by cgrandin** [comment]
I double-checked and all the values in the `extra-mcmc` output show this to be correct. That is, the median of the value in the 8,000 report files is indeed that high for 2023 for that bridge model (and the others actually). The only way I can make sense of it is that the 2024 biomass estimate is actually the same as the end of year 2023 biomass, so that biomass goes up in the same year as the survey index fit, it's just at the end of the year. The 2023 survey point is in 2023 so I assume the model is trying to fit that point for 2023, it's just not able to do a very good job of it this time.

Is that a correct way of interpreting this?

If interested, the values come from the 8,000 Report_mce_XXXX.sso files inside the mcmc/sso dir of the model path. Inside those, it is from the `Exp` column of the `INDEX_2` data frame (fleet 2). All those values are loaded, then the median is taken, then it is divided by 1e6. If you want to see the calculated values (substitute `index_lo` of `index_hi` instead of `index_med` to get CI values):

```bridge_models[[2]][[4]]$extra_mcmc$index_med |> filter(fleet == 2) |> print(n = 100)```

![image](https://github.com/pacific-hake/hake-assessment/assets/4551051/9cf0c5f7-515a-4090-a5c3-19ea64d9fe6f)

**Comment by aaronmberger-nwfsc** [comment]
We are all good here.  Thanks for looking into this Chris.  The delay does indeed seem correct b/c the survey is a summary of age-2+ biomass, not spawning biomass.  Because fish tend to mature between 2 and 3 and beyond, it makes sense that the survey would first pick up on the uptick before all that biomass becomes mature and we see the SSB uptick.

Closing as this was a good thought process, but not needed as it is correct.
