### ISSUE TITLE
Table 4 (summary of fishery sampling) only goes up to 2022, not 2023

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#1147]
This is because `data-tables/fishery-sampling-history.csv` only goes up to 2022.

In 2023 assessment I see that the 2021 and 2022 values simply match those in the fleet-specific tables (suggesting they could just be copied over). But the 2022 values in this year's assessment don't actually match between the tables (and some have been updated from last year). 

So I'm not sure where the 2023 numbers for  `data-tables/fishery-sampling-history.csv` should come from.

**Comment by cgrandin** [comment]
I propose that we do away with this file and have the function that creates the table extract the values from the `*_age_df` variables.. 

Some of the values are different between the `*_age_df` tables and the fishery-sampling-history.csv file. This is because the extractions have changed the data over time. We are still reporting the old values in the table in the assessment. I can do this if everyone is ok with it.

To see the differences for 2022 US CP:
```
us_cp_age_df |> filter(year == 2022)
sampling_history_df |> filter(Year == 2022) |> unlist()
```

Reduce bloat!

**Comment by cgrandin** [comment]
Actually, we can't do as I proposed above yet because the US age proportion tables only have back to 2008 and the sampling table goes back to 1975

**Comment by cgrandin** [comment]
Fixed it for this year manually. Making it a 2025 milestone to consider the above method.
