### ISSUE TITLE
revise selectivity write-up

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#323]
The selectivity write-up could use a few changes, regardless of whether on not we switch to a new parameterization (issue #310 ).

Among the changes that could be useful are
- adding text and equations about logistic transformation used when adding deviations over time. This was present in all 3.24 models, but not described previously, due to an oversight that was only noticed when I was converting to 3.30.
- clarifying potentially confusing description where for fishery selectivity, selectivity (S_a, the derived quantity) is fixed at 0 for age 0, while the parameter for selectivity at age 1 (p_a, the estimated quantity) is fixed at 0 for age 1. The parameter could be fixed at any other value, 0 is just a simple choice. Survey selectivity is fixed at S_a = 0 for both ages 0 and 1, and has p_a = 0 for age 2.

**Comment by aaronmberger** [comment]
yeah, if the selectivity of Amin (survey and fishery) is fixed at a reference level (0 in this case) in parameter space and others estimated relative to that reference, it should be fine as long as the relational nature of the reference level to all other estimated levels remains after back-transformation and rescaling (max selectivity is 1).  It sounds like this is the case (as I'm sure it would be) - maybe just use the term 'fixed to a reference level (0 in this case)' instead of fixed at 0.  Or maybe it's just my confusion...

**Comment by andrew-edwards** [comment]
Just a reminder that in the Data section last year there are two pages (39-40) on the selectivity function - presumably that would be a starting point.

**Comment by taylori** [comment]
The write-up of selectivity (pages 39-40) should be expanded to include discussion of the extra transformation for the time-varying parameters that was present (but undocumented) in the 2017 model, and no longer available in SS version 3.30 (illustrated in the figure below, previously shared by email).

I previously stated that the slope was about 0.135, but taking the derivative of the equation involved reveals that, ignoring the the tiny added constants it's actually 1/7 ~ 0.1428. This value implies that the old phi = 0.20 should be converted to phi = 0.20*7 = 1.40, rather than the 1.50 value found by trial and error used in previous conversions to 3.30. Indeed, an SS 3.30 model with phi = 1.40 matches our 2017 model using 3.24 a tiny bit better than those before, so I will use that value in the updated bridging steps, starting with model 2018.31.
![selectivity_transformation_illustration](https://user-images.githubusercontent.com/4992918/35595618-285805aa-05cc-11e8-9b0f-f4809a8408cc.png)

**Comment by taylori** [comment]
The function `randWalkSelex.fn` (in utilities.r) replicates the calculation of the selectivity from the parameters values with or without deviations. In commit f697a82 I just modified to remove the parameter transformation described in my previous comment on this issue, so that the calculations will work for our new base model. If we need to represent selectivity for earlier models, we can use change the new argument `transform=FALSE` to `TRUE`.

**Comment by aaronmberger** [comment]
Ian:

is this statement still true or has something changed in new version of SS (I didn't think so but thought I'd check)...

"forecasted catches are removed using selectivity averaged
over the last five years"

**Comment by taylori** [comment]
Yes, still true thanks to this line in forecast.ss:
```
#_Fcast_years:  beg_selex, end_selex, beg_relF, end_relF, beg_recruits, end_recruits  (enter actual year, or values of 0 or -integer to be rel. endyr)
 -4 0 -4 0 -999 0
```
A change in 3.30 is the addition of the 5th and 6th inputs there, which control the reference years for recruitment in models where you have time-varying stock-recruit parameters due to regime shifts or something like that (the -999 to 0 default just says average over the whole time series). Our model has time-invariant R0, h, and sigmaR so those new settings don't matter

**Comment by taylori** [comment]
I think this is adequately addressed to close the issue. I have a few additional ideas for further improvement but I think the minimum necessary for a complete document has been done.

**Comment by kellijohnson-NOAA** [comment]
[Rick Methot notes](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/105), when looking at a very long forecast from the hake model that ...
```
I note that this model has time-varying selectivity parameters and that the forecast selectivity
is set to average over the last 5 years of the time series.
This means that selectivity in the forecast is much less variable than selectivity in the time series.
An alternative configuration would have the selectivity parameters continue to have random
devs into the forecast period and to change the forecast selectivity to use annual calculations
rather than an average of recent years. I tried this alternative and, as expected,
it had a large impact on the variance patterns in the forecast.
```
- [ ] set up a model run where the forecast is based on random deviates to see how much the forecasts change
- [ ] determine if selectivity used the 2dAR process how this would change or need to be set, do we currently do anything different for the sensitivity run with 2dAR selectivity for the forecasting?
- [ ] RM also noted that the maxF in the forecast is set in the control file to be 1.5. Just something to think about, regarding if it should be increased or not?
