### ISSUE TITLE
Aren't there two sets of p_a parameters?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#377]
Bottom of p39 says there are p_a for the fishery and p_a for the survey. 

1. So does that mean there are actually two p_a^{high}  and p_a^{low} values? There may not be.

2. And then shouldn't (8) be summed over the fishery and the survey? Or, to save adding extra notation, this can just be explicitly mentioned. 

3. Also, okay if I change p_a^{high} to just p_{\mbox{high}}. I'm currently co-writing a manuscript on notation, and using subscripts that don't represent powers is one of our no-no's!

**Comment by taylori** [comment]
1. Yes, two sets, so we could subscript for fleet _f_ or something like that if needed, but it might be cleaner to just explain that in the text. The bounds are the same for the two fleets (-5 to 9 as shown in Table 17).
2. Yes, equation (8) could either have an _f_ subscript on the _L_ or refine text to note that this contribution is for each fleet.
3. Yes, I didn't know about \mbox but that sounds like an improvement. Happy to have things cleaned up.

Also, I just noticed typos in my new equation (12) so will fix that right away.

Please edit as you wish or instruct me on any changes that you want me to make.

**Comment by andrew-edwards** [comment]
Thanks - I can do the edits. Yes, usually I'd have a fleet subscript, but since we don't have other equations it will be simpler to just state that it occurs twice, and the bounds are the same for the two fleets.

**Comment by taylori** [comment]
Equation (12) fixed in 26e528d1ab96e11503daf3f040e84220a3ec6aa9

**Comment by andrew-edwards** [comment]
Ian - please take a look through the above commit. I did the changes as specified in 1, 2 and 3 above, plus a few more.

One thing - it's not clear what the value of 7 is referring to in the penultimate sentence.

**Comment by andrew-edwards** [comment]
btw, Ian commented on \mbox above. I've always used that but I think \text is better (seems to scale properly), which is what you've used elsewhere.

**Comment by taylori** [comment]
Changes all look good to me. 
I think the capital \Phi (issue #387) is an improvement, but it needs to be added to equation (8) as well.

This origin of the 7 in this phrase at the end is indeed a bit unclear:
> The resulting value of 7 at the mid-point between the bounds is an approximation to the relative impact of a deviation in the logistic parameter space to one in the standard parameter space. The resulting value of Φ = 1.40 approximates the value of φ = 0.20 used in the transformed parameter space in the 2017 assessment.

7 is the derivative of p_{ay} with respect to \tilde{p_{ay}} at \tilde{p_{ay}} = 2, the mid-point between the bounds of -5 and 9. However, since this transformation is applied to each p_a for ages 2 to 6, and those values vary between about 0 and 2.5 as shown in Figure 52(a), the derivative isn't exactly 7 for any age. And the slope is only a linear approximation to the logistic anyway.

Another way to define the 7 would be to say it's the horizontal arrow is about 7 times longer than the vertical arrow in the figure pasted into this comment: https://github.com/cgrandin/hake-assessment/issues/387#issuecomment-364605940.

My struggle with this is to find the balance between being precise about exactly what changed, and not getting into the weeds on a bunch of stuff that in the end really doesn't matter much since the two models line up pretty well.

In hindsight, it was a mistake not to notice the logistic transformation when time-varying selectivity was explored in the MSE in 2013 or 2014, discover that it didn't make any significant difference other than changing the interpretation of phi, and get rid of it back then.

**Comment by taylori** [comment]
Sorry, I forgot to mention that I already added \mbox to a few other places, such as equation (9), where I do see that the "a_max" looks a bit strange. If you have time to go through and change to \text, please do, or delegate to me to do so.

**Comment by andrew-edwards** [comment]
Good spot about eqn (8). Will do that now.

Can we just omit the sentence about the 7?  The important bit is the resulting Phi=1.4.  You have the figure in case anyone wants more details.

**Comment by andrew-edwards** [comment]
That \mbox doesn't seem to work in limits of a product (yes, I saw that you did it - saved me trying). Am getting it sorted. Should have been simple.....

**Comment by andrew-edwards** [comment]
I think this is all good now. I just said something like \Phi = 7 \phi   yesterday. I should leave it to Ian to confirm and close though.

**Comment by taylori** [comment]
Looks good.

**Comment by andrew-edwards** [comment]
Clarify this. Kelli's noted that the survey selectivity isn't time-varying, so this should be more explicit. Think about....
