### ISSUE TITLE
Any use for alternative heatmaps?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/hake-assessment#505]
The new heatmap for weight-at-age looks good and is nicely integrated into the rest of the code.
Recent discussion about it, reminds me that as part of the exploration of the accuracy of the early weights, I created a figure where the numbers showed the sample size instead of the weight, and another showing the pattern of mean length-at-age (both below).

Is there any value in using these for either the document or a presentation to the SRG? If so, they should be updated to account for the more complete set of samples you've all put together for this 2019 model.

![empirical_wtatage_2018_alldata_1b_nointerp_numbers](https://user-images.githubusercontent.com/4992918/52141287-1677f700-260a-11e9-81b6-3ed6262c3813.png)

![empirical_lenatage_2018_alldata_6_nointerp](https://user-images.githubusercontent.com/4992918/52141274-0c55f880-260a-11e9-834f-961c44a2cb95.png)

**Comment by aaronmberger** [comment]
Yes, thanks Ian for the reminder.  These have been recreated/updated (thanks to your code additions) in our data extraction.  I guess I was originally thinking we would present them at SRG, but we can add them to the document this year as discussion will be heavily on wt-at-age and fecundity-at-age I suspect.  Updated figures are below.
![empirical_wtatage_2018_alldata_1b_nointerp_numbers](https://user-images.githubusercontent.com/7946234/52142593-edf1fc00-260d-11e9-8214-e9b5c07d3755.png)
![empirical_lenatage_2018_alldata_6_nointerp](https://user-images.githubusercontent.com/7946234/52142630-0530e980-260e-11e9-93c8-27ab546ec9da.png)

**Comment by andrew-edwards** [comment]
First one would be useful. I think should go into the document as should be fairly easy (rather than 'save for SRG meeting' - gets a bit complicated then).

Not sure we need length one though? Would it be useful? I'm unsure....

Glad you like the new heatmaps - shame they're currently wrong ;)   #504

**Comment by aaronmberger** [comment]
Okay, first (sample sizes) into the document - so will upload eps file for that then, right?  The length-at-age one I will use in the presentation about wt-at-age explorations/analysis more generally - so just used in presentation. It is useful to make the point that similar pattern is show for lengths so not solely a "early year not accurate weighing scale thing - one hypothesis about early year weights"

**Comment by andrew-edwards** [comment]
Sounds good. If Chris tries to delete your hardwired .eps I'll stop him ;)

It was good that we saw your weight-at-age one though as we had to update the interpolated values (and mean).

**Comment by taylori** [comment]
Makes sense.
In the future, the new code (being edited as part of #504) could be modified to take a matrix of sample sizes as an optional input so that it could produce something similar to the first figure, but that's surely not a high priority at this stage.

Yes, primary purpose of length-at-age figure was just to show that the weights weren't biased high--year/age combos with heavy fish also had longer fish.

Among the benefits of the sample size figure is to show that the 1975 had tiny sample sizes, and the really heavy age-15+ cell in 1976 was based only on 11 fish.

**Comment by aaronmberger** [comment]
Also interesting that most of the "super-weight" fish from 1975-1981 are all from US foreign fleet...

**Comment by cgrandin** [comment]
This is great. When I re-wrote the heatmap code I used the values in wtatage.ss, where would the sample size data for these be? I'm just thinking about moving forward we should add those data and the code to the repository

**Comment by aaronmberger** [comment]
It's internal to our weight at age code, which we are planning to move to this repository rather than our private US hake data repository.  This will occur later in 2019.

**Comment by andrew-edwards** [comment]
Closing but added 2020 milestone regarding adding some code to this repo...

**Comment by cgrandin** [comment]
@kellijohnson-NOAA if you're happy with this can you close it - I'm not sure if you added code but everything is fine as is in my opinion.
