### ISSUE TITLE
Need to explain big increase in recent estimated recruitments compared to last year's assessment

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#629]
e.g. we now think there were 1.76 billion more fish spawned in 2010 than we did in last year's assessment. That's based on medians - confidence intervals also increase. 

I added some calculations (and commented example plots) in custom-knitr-variables.R, and preliminary text in exec summary. I was going to carry on doing a quick figure (showing medians and credibility intervals), but realise it will get done automatically when bridging model plots are updated (see commit that will get referenced below; it's on my andy-dev branch for now). So, we do need to 
- [x] make sure the bridging plot of recruitments clearly shows the increased 2010 estimate; may even need to make it just one bridging step in the plot
- [x] add something to main text to explain this
- [x] edit exec summary as necessary

Seems to me a big increase, so should be highlighted.

**Comment by andrew-edwards** [comment]
Related - just figured this out:
![image](https://user-images.githubusercontent.com/6977190/73501841-f7768700-437b-11ea-981a-f38d8e51035e.png)

Looking at medians of recruitment (billions of fish):
```
Assess.yr      1980 rec        2010 recr
2019               16.6                13.5
2020               16.3                15.3
```
So 2010 estimated to be much higher than we estimated last year, but 1980 not changed. Hence 2010 now has higher chance of being the largest.

**Comment by aaronmberger-nwfsc** [comment]
Re: bridging recruitment.....   
And bridging models are conducted in MLE world so results between last year and this year 2010 recruitment may differ (in an absolute sense) at a different level than with MCMC.  Nonetheless, our bridging models show that even a small change in rec devs for 2010 creates this small (but not insignificant) absolute difference for estimated 2010 recruitment.  It looks like that slight increase occurs when adding the 2019 survey compositions.  So I would expect that survey comps for 2010 year class were larger than the model would have otherwise expected and so had to increase recruitment.  It will be interesting to see if this is detectable in the squid plot.

**Comment by aaronmberger-nwfsc** [comment]
I do note that our current bridging figures can be small and hard to interpret small changes such as this issue.  At the same time, I don't really want to create 5 figures for every bridging set of steps (thus I like the 'layout' of the 5 current figures as one.  I suggest we leave the bridging figures as they are in the document but then hone in on specific figures when presenting to the SRG.

**Comment by andrew-edwards** [comment]
Aaron wrote some text in exec-summary that I already copied into main assessment section. Agree that the 2010 bump may not show up in bridging plots.

Aha - Aaron mentioned squid plot - there is a slight bump in 2010 one. I'll make sure to add something when reading through. So leaving open for now....

**Comment by andrew-edwards** [comment]
No tweaks to bridging plots, added text regarding squid plot in the above commit. Haven't crunched the numbers, but squid plot indeed suggests that it's the final year of data rather than model tweaks that bump up the 2010 recruitment.
