### ISSUE TITLE
What is tuning?

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#645]
Was going to say 'do we still have it'? I just took out some text (which Kelli had also suggested be removed), 336b5dd . But we still say: 

```
Tuning quantities remained relatively consistent from 2018 to \Sexpr{assess.yr}.
```
But what is tuning now? It's not mentioned anywhere in the document, except Figure 17 caption as the final bridging model. Should explain it somewhere if it's still done. (Doesn't the DM stuff somewhat negate it).

**Comment by aaronmberger-nwfsc** [comment]
Tuning predominantly means doing the following:
1. iteratively adjusting data weights
2. checking on r4ss output metrics to see if the recruitment bias correction still seems reasonable
3. updating the years for which bias correction is applied (usually just adding one more year to the main rec period)
4. checking on r4ss output metrics to see if sigmaR still seems reasonable (when not estimated as in our case)

#1 for use now doesn't occur (due to D-M) and this year #2 and #4 were unchanged and for #3 we just added on year (somewhat standard).  So I would be fine not referencing tuning at all given #1 is now 'automated' via being a parameter

**Comment by aaronmberger-nwfsc** [comment]
I guess it also means checking that parameters are not hitting bounds, etc.... but that is just normal stuff

**Comment by aaronmberger-nwfsc** [comment]
oops, forgot about hashtags here... disregard links

**Comment by andrew-edwards** [comment]
Chris just said he's never seen it explained so nicely! Shame it's about to be purged.... Okay, I'll take it out, thanks.
