### ISSUE TITLE
Update table about ovaries collected

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#648]
Table needs 2019 row 
"Number of Pacific Hake ovaries collected for histological analysis"

**Comment by andrew-edwards** [comment]
We didn't update the maturity ogive, so if we do update the table just have to clarify the caption (that 2019 'collected' were not analysed).

**Comment by aaronmberger-nwfsc** [comment]
No new analysis was done because or maturity expert was filling in for another position much of last year.  I have just sent her a reminder email about sending us sample sizes.

**Comment by aaronmberger-nwfsc** [comment]
The table has been updated, but I think it still only includes NWFSC samples (not DFO survey samples since 2018).  Maybe we just leave adding those for another time.  I'll leave it up to Chris to close if he agrees or close when DFO samples are added.  We do talk about these samples and the ability to do histological analyses in the SRG response section.

**Comment by cgrandin** [comment]
I'm going to leave this as-is for now. I will try to get the number sampled on the Canadian part of the survey by interrogating the database and asking Stephane if he has the information and add it then.

**Comment by cgrandin** [comment]
This isn't going to happen before the submission date tomorrow Feb 10. I will continue to try and get the numbers post-submission but just letting you know.

**Comment by cgrandin** [comment]
A couple hours after we submitted the doc, I got information from Stephane about ovary samples. 15 were collected on the 2019 survey in Canada. That is all, ever.

**Comment by aaronmberger-nwfsc** [comment]
Kelli and I have now received an updated table on female and male gonad samples from Mellissa Head (no surprise but all 0's for 2020).  Chris, can you provide any updates for Canadian gonad samples (ovaries only I suspect for 2020 and/or previous years).  Let's keep this open until all gonad samples are updated so that our associated table in the document is also updated. 

As an aside, but relevant for response to SRG requests, I'm following up with Melissa Head and company about the status of potentially collaborating with DFO to get Canadian samples processed.  Sounds like there has already been discussion on this, but I'll keep you informed.

**Comment by cgrandin** [comment]
There aren't additional samples for Canada

**Comment by aaronmberger-nwfsc** [comment]
Any sample updates from before 2020, or is what we have already current for Canada?

**Comment by cgrandin** [comment]
It's all up-to-date for Canada. All 15 samples total from 2019

**Comment by aaronmberger-nwfsc** [comment]
Kelli has updated the table for this year, so closing...
