### ISSUE TITLE
Make SSplotComparisons subplot 14 the same as others

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#660]
It would be nice to make the x-axis of this plot match the others. It is the survey index one (subplot 14).

See bridging plot - Fig 17, and sensitivity plots 44 and 50. I know the survey was in 2019 but it would be nice to make the plot go to 2020.

**Comment by kellijohnson-NOAA** [comment]
I think that we can pass "endyrvec" to `SSplotComparisons` to get it to work. Should we pass the same endyr to all plots so that they are more comparable as you scroll through pages?

**Comment by cgrandin** [comment]
Sure, except the survey index should probably start in 1995 or the plot will be crazy small. ```endyrvec``` could end with ```assess.yr```

**Comment by cgrandin** [comment]
I can do this if you're busy Kelli, it's just cosmetic anyway

**Comment by kellijohnson-NOAA** [comment]
r4ss doesn't currently change the x-axis of the index plot. I changed r4ss, but I am worried about the result
![index](https://user-images.githubusercontent.com/4108564/74095917-7f5f3e00-4aac-11ea-83d2-a8b6831f1249.png)
because if you remove the padding (i.e., `xaxs = "i", `) then the points are hard to see if they are at the extreme ends of the axis. What do you think @cgrandin?

**Comment by cgrandin** [comment]
I couldn't get it to change easily by passing 2020 to endyrvec and since you can't make it happen easily I would say we can drop it for now. I'd rather see the points than have end years line up! Thanks for checking but I'll close it.

**Comment by kellijohnson-NOAA** [comment]
![image](https://user-images.githubusercontent.com/4108564/74096180-3ad5a180-4ab0-11ea-8af2-89f20523682c.png)
