### ISSUE TITLE
In adnuts appendix, why are the histogram diagnostics figures different?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#663]
Figure H5, which is read in from a graphics file vs. figure H18 which is constructed using the usual method in knitr are different. 
If figure numbers change, search for "distribution across lag times"
This is the code that the knitr chunk is running:

```
  mcmc.stats <- mcmc.nuisance(model$mcmcpath,
                              run = "",
                              labelstrings = c(model$parameters$Label,
                                               "SSB_",
                                               "Bratio_"),
                              bothfiles = TRUE)

```

**Comment by aaronmberger-nwfsc** [comment]
this is what created the graphic file:
mcmc.nuisance(dir="...\\2020.01.31_nutsMCMC\\",run="mcmc\\")
So the difference must be in the parameters (estimated and derived) that are used to create the plot.  I think our knitr chunck uses specifically 
labelstrings = c(model$parameters$Label,
                                               "SSB_",
                                               "Bratio_")
where the default (used in the graphics version) is labelstings = "all" in both 
file = "posteriors.sso", file2 = "derived_posteriors.sso". 
See [https://rdrr.io/cran/r4ss/man/mcmc.nuisance.html](url)


I haven't built again yet so don't see the other version, but hopefully they are pretty close I would assume.  I guess I would use our knitr chunck version (and ditch the graphics version) so that the adnuts figure is comparable to the base model one (and age-1 survey one).

**Comment by cgrandin** [comment]
They do look quite a bit different..
This is the one with the code in the knitr chunk:
![image](https://user-images.githubusercontent.com/4551051/74095644-ac115680-4aa8-11ea-98f1-d359e04c98fe.png)
This is the graphics file:
![image](https://user-images.githubusercontent.com/4551051/74095655-c51a0780-4aa8-11ea-883c-91414867eb61.png)

**Comment by aaronmberger-nwfsc** [comment]
Hmm something is weird here because here is the shinystan related figure for effective sample size:

![image](https://user-images.githubusercontent.com/7946234/74095873-b2550200-4aab-11ea-9c3f-324c075d00df.png)

**Comment by aaronmberger-nwfsc** [comment]
which it's hard to tell with different bins but looks pretty close to the graphics version

**Comment by aaronmberger-nwfsc** [comment]
I'll look more into these differences tomorrow.

**Comment by aaronmberger-nwfsc** [comment]
Difference is in the labelstings. One is using ALL estimated and derived parameters and the knitr chunk is using only estimated and derived SSB and Bratio.  So the version our knitr chunk is using is a subset of the other.

**Comment by cgrandin** [comment]
OK, I can change that. I'll work on it
