### ISSUE TITLE
Estimated recdev vs predicted recdev

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#665]
Sec 3.2 paragraph 3 mentions recruitment but doesnt explain what is done for 2019 just before and after. Also the correlation plots for mcmc have correlation with the years that aren't estimated, should we change that to be estimated years?

**Comment by cgrandin** [comment]
In the posteriors.sso file they are Main_RecrDev_* up to 2018, then Late_RecrDev_2019 for 2019, then Fore_RecrDev_* for 2020-2022. What does Late_RecrDev_2019 mean in the SS context? I'm asking because I don't actually know what happens here so any insight would be great!

```
"Year-specific recruitment deviations were estimated from
1966–2018 as well as the years 2020, 2021, and 2022 for purposes of forecasting."
```

**Comment by aaronmberger-nwfsc** [comment]
Regarding section 3.2 para 3: The sentence says: "Year-specific recruitment deviations were estimated from 1966–2018 as well as the years 2020, 2021, and 2022 for purposes of forecasting."  The first part is correct, but the second part is incorrect.  In fact, we fix recruitment devs at the average (dev of 0) for the last year of the assessment (2019) and the three forecast years (2020-2022).  

And yes, it does seem weird that we show mcmc correlation for 'Recruit dev. 2019', as that is fixed at 0 - glad it shows no correlations!  The only reason it has any variance on that axis is because of difference in R_0 and h across MCMC which changes the recruitment for which a fixed deviation of 0 corresponds to.  Not sure it is worth changing at this point.

**Comment by kellijohnson-NOAA** [comment]
If we took out 2019 in the correlations plot it would give more room for the D-M parameters.

**Comment by cgrandin** [comment]
I left 2019 in the recruitment devs pairs plot but if you change the end year in the function call in ```appendix-mcmc-diagnostics.rnw``` you can remove it. I am closing this but if you all feel like it needs to come out, go ahead.

```
make.mcmc.diag.pairs.plot(base.model,
                          inc.key.params = FALSE,
                          recr = (end.yr-10):(end.yr-1))
```
