### ISSUE TITLE
Since the phase plot has changed, what about those values in tables?

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#670]
@andrew-edwards changed the phase plot to show Rel. Fish. Intensity as (1-spr(t-1))/(1-spr(40%)), so the numerator is now from the year before the denominator. Do the tables (24 and 25) need to be changed to make these comparable? The question may come up as now they don’t line up.

**Comment by cgrandin** [comment]
Example: 2020 appears in the plot but the table has it as a blank because it’s defined differently

**Comment by aaronmberger-nwfsc** [comment]
For the plot, we do now say exactly what the labels refer to so I think we are okay.  And I think the values need to stay in the table as they are.  I'd suggest that we add more to the table captions saying that spawning biomass is at the start of the year and relative fishing intensity is calculated over the entire year (or accumulated and reported at the end of the year), or something similar.  Further, I suggest we ask the SRG if they like the way the phase plot is reported or if they have any suggestions to ease interpretation - never hurts to turn the tide and ask THEM questions, ha!

**Comment by aaronmberger-nwfsc** [comment]
If okay, with folks I can add caption text.

**Comment by cgrandin** [comment]
@aaronmberger-nwfsc I like the way you think because I checked and to change those values would be a nightmare at this stage. the model outputs that ratio as 'SPR' so we would have to re-run the base model mceval at a minimum.

**Comment by aaronmberger-nwfsc** [comment]
thumbs down to additional mceval - not the way I think - :)

**Comment by cgrandin** [comment]
OK, so I'll close this. I just wanted to give everyone a heads-up

**Comment by andrew-edwards** [comment]
Just say in Table captions that biomass and relative fishing intensity both refer to year $t$. Or could just change B0 to $B_t / B_0$ and the final (1-SPR) to (1-SPR$_t$) to be explicit. We haven't used terminology SPR$_t$ much, but we do in the phase plot axis (where it's SPR$_{t-1}$).

**Comment by aaronmberger-nwfsc** [comment]
Okay, after considering Andy's suggestion I've changed my mind.  The tables are actually correct (you just need to know the definitions - which is why we have a glossary).  For SSB it says beginning of year, so I was thinking of just adding for the definition for fishing intensity that it is across the whole year (i.e., end of year total).  I think we are then covered.  The phase plot is a bit different, but we describe that in the caption.  So I'll only add the timing part to the definition for fishing intensity and then we should be good.

**Comment by cgrandin** [comment]
One other thought.. And this is relatively easy to do. Bump the table values down by one row. Redefine the caption and the plot and tables will be directly related without confusion.
So 2020 in the table would have 76.4%, 2019 would have 75.4%, etc.

**Comment by andrew-edwards** [comment]
No, I say keep things defined as year t. Then only the phase plot has the SPR for year t-1.  You'd have to change figures as well if you start changing definitions....

**Comment by aaronmberger-nwfsc** [comment]
I'm not a fan of that, because the literal interpretation would be fishing intensity in 2020 is 76.4%, but we don't include catch in 2020 so how would we know fishing rates.  I think the glossary thing is the easiest.  Also, the way we have it conforms to the way most people do it.  The only reason this comes up is because of the phase plot.  But we can ask SRG....

**Comment by andrew-edwards** [comment]
It's more fun to also give Chris a thumbs down ;)

**Comment by cgrandin** [comment]
Luckily I know how to deal with rejection haha. I'll stop trying to create more work now. Roll with your idea.

**Comment by aaronmberger-nwfsc** [comment]
Maybe someone who has taken Trevor's R graphics class (or the instructor himself) can come up with a better way than the phase plot to portray such info (i.e., fishing and biomass based reference points at the same time).  The last time a group came up with such a plot the location where they did became the plot name (Kobe, JP) so maybe it may become a Johnson plot!?!
