### ISSUE TITLE
Trevor comments

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#683]
see attached...
[Branch 2020 Minor comments for assessment team.docx](https://github.com/pacific-hake/hake-assessment/files/4223339/Branch.2020.Minor.comments.for.assessment.team.docx)

**Comment by andrew-edwards** [comment]
I knew he'd mention adnuts/ADNUTS/NUTS etc., ha ha. I'd noticed we weren't fully consistent, but didn't get round to thinking about or mentioning it (other things seemed more important). 

Most look sensible and doable. Some are a bit picky, and I think are okay to not worry about in a 250-page document. Appreciate his thoroughness!

**Comment by cgrandin** [comment]
I made a checklist from his Word document.
Check each off when completed. Close issue when all are checked.

- [ ] p. 4 ADNUTS -> adnuts.  (also elsewhere including p. 17). The adnuts package is a way of using the no-U-turn sampler, so should either be the adnuts package (ref. Monnahan & Kristensen 2018) or the NUTS algorithm (for an explainer, see Monnahan et al. 2017; for citation to the actual algorithm, see 
Hoffman, M.D. & Gelman, A. (2014) The no-U-turn sampler: adaptively setting path lengths in Hamiltonian Monte Carlo. Journal of Machine Learning Research, 15, 1593–1623.); for applications to fisheries models see Monnahan et al. (2019). 

- [ ] p. 8, line 2 Markov Chain Monte Carlo -> Markov chain Monte Carlo

- [ ] p. 12, line 3 “where the proportion of age-9 fish was higher than what the 2019 assessment model results would have otherwise suggested given mortality” -> “in which the proportion of age-9 fish in 2020 was higher than predicted by the 2019 assessment model given mortality”

- [ ] p. 16 last line: “is above its target of 1.0 at the end of 2019 is”  both occurrences of “is” should probably be “was” given that this sentence refers to past catches in 2019 unlike the previous sentence for current biomass in 2020. 

- [ ] p. 17 last line: “and numerous sampling” -> “and intensive sampling”.

- [ ] p. 17 last line: “existing age-1 index and why the estimates” -> “existing age-1 index. This is why the estimates”.

- [ ] Tables g, h, i, j: numbers should be right aligned, not center or left aligned. 

- [ ] p. 24 line 14 “Utilize” -> “Use”. 

- [ ] p. 26 line 18 “aforementioned” -> “default”. 

- [ ] p. 30 Figure 7 is not summarized or cited in the text (depths in the Canadian fleet). 

- [ ] p. 31 Figures are referenced in the order 8, 13, 12. It would be good to check that all figures are referenced, and are referenced in the order they appear in the figures section. 

- [ ] p. 34 line 20 “Since 2016, the 2010 and 2014 cohorts have showed up as significant proportions” -> “Since 2016, substantial proportions of the catch have come from the 2010 and 2014 cohorts”

- [ ] p.34 line 21 & line 23 “was” should be “is”. 

- [ ] p.34 line 26 “, followed by the 2010 cohort (23%)” -> “and the 2010 cohort (23%)”. 

- [ ] p. 34 line 27-28 “In 2019, the 2014 cohort was the largest (32%), followed by the 2016 cohort (21%), followed by the 2010 cohort (19%).” could be “This pattern continued in 2019 when the 2014 cohort was the largest (32%), followed by the 2016 (21%) and 2010 (19%) cohorts.”

- [ ] p. 36 lines 24, 25 “were post-stratified” and “frequency was used” should be changed to present tense “is” to match the rest of the paragraph. 

- [ ] p. 37 line 7 “a full time-series of consistently analyzed survey biomass” should be “a full time-series of consistently analyzed survey biomass since 1995” since the earlier acoustic surveys are not included. 

- [ ] p. 39 para 1 end could be reworded to “For the current assessment, both forecast weight-at-age and forecast selectivity is based on the respective means from the most recent five years (2015–2019), for consistency.”

- [ ] p. 40 line 21 If I interpret this correctly, “In the 2006 and subsequent assessments” should be “In the 2006–2010 assessments”.

- [ ] p. 40 line 28 Delete “Models have had great difficulty in making predictions that mimic the observed data.”

- [ ] p. 40 section 2.3.4 In some places it appears as if there are two spaces after a period, and in other places one. It would be good to standardize to one space.  

- [ ] p. 41 2.4.3 “as described by” should be “and are described by”

- [ ] p. 43 para 2: unclear from this paragraph whether the Dirichlet-Multinomial also requires iterative adjustment of multipliers, or whether it immediately gets to the effective sample size correctly. 

- [ ] p. 45 last line: change to “… following two structural changes: (1) a nearly uniform… ; (2) estimated recruitment deviations…”

- [ ] p. 46 line 30 “is fixed at a value of 1.4” -> “is fixed at 1.4”

- [ ] p. 46 last line. Consider also mentioning here that central results are the 50% quantile (since this could also be the mean or mode) of the posterior distribution. 

- [ ] p. 54 line 25 “The second set of bridging steps were conducted” -> “second set… was conducted”

- [ ] p. 54 second last line: “and a decreasing” -> “and decreasing”. 

- [ ] p. 54 last line “because there was now fishery data” -> “because of the addition of fishery data” (to avoid the debate over whether data are plural or singular). 

- [ ] p. 56 fourth last line: “The 2019 survey was the first time the survey was able to sample” -> “The 2019 survey was the first to sample”. 

- [ ] p. 58 line 29 “was higher than what the” -> “was higher than the”. 

- [ ] p. 59 line 10 “only one year of fishery data are used” -> “only one year of fishery data is used” (since “of fishery data” is ignored when deciding on case). 

- [ ] p. 59 “Figure 32 and and” -> “Figure 32 and”. 

- [ ] p. 61 line 5. Consider rewording to “Most key derived quantities… are smaller (Table 27).”

- [ ] p. 64 line 13 “probabality” should be “probability” 

- [ ] p. 67 second last line “individuals to to predict” -> “individuals to predict”. 

- [ ] p. 68 line 5 “retrospective bias is was predominately positive” -> “retrospective bias was predominantly positive”

- [ ] p. 68 line 15 “appears to maybe be more similar to the 2008 cohort rather than the 1999 cohort” doesn’t seem quite accurate. The 2014 cohort line is above both the 2008 and 1999 lines, which are identical at that point in time. Reword to “is above the 2008 and 1999 cohorts at a similar point in time.” 

- [ ] Table 5 & 14: numbers should be right aligned. 

- [ ] Table 16: “additional value” should be “additional variance”. Also “Number estimated” should be “Number of parameters”, to avoid the ambiguity involved in thinking that this is the best estimate of the parameter in question. 

- [ ] Table 21: could be simplified by deleting columns with ages 7-20 and renaming age 6 to age 6+. 

- [ ] Table 30: the caption is missing spaces in “Table 29.Values” and “than theF40%”

- [ ] Table 35: the numbers in the Base Model and NUTS column are exactly identical, which seems unlikely. 

- [ ] Figure 11: would it be hard to instead plot the Bayesian estimates and 95% credibility intervals of age-1? Instead of the MLE values. 

- [ ] Figure 15: top left panel it is not possible to see the unfished mean spawning biomass since it is clipped by the figure margin on the left (also Figure 16-17, 52-54). Some y-axis tickmark values are horizontal and others vertical (also Figure 16-17). 

- [ ] Figure 19: lower panel. Make this plot much skinnier so that it better matches the fishery age composition plot. 

- [ ] Figure 21: the posterior for the bottom panels needs smaller bin widths. Also it might be more meaningful to plot prior and posterior on the multiplier of sample size rather than on θ itself. I guess that would be true of the tables as well. 

- [ ] Figure 43-50: since the plots are fairly complex, there should be a legend on each page of the document rather than referring to previous pages.

**Comment by aaronmberger-nwfsc** [comment]
Let's not worry too much about these before SRG.  I may work on some Monday night and/or during the SRG week if I have time, but I see no rush on these.  It would be nice to have the ones that we want to do (I see some that we may not want to do) done by next Friday so we can turn the final assessment document around fairly quickly.

**Comment by andrew-edwards** [comment]
We did the ones that are checked off, but not the ones that show up as bullet points. May be worth revisiting some of the latter next year (though most aren't crucial).

**Comment by kellijohnson-NOAA** [comment]
Should I put the ones that we are going to do in the future in a new issue or should we just change the milestone of this issue to be next year?

**Comment by kellijohnson-NOAA** [comment]
Regarding Figure 11 being in MCMC (right) MLE (left). I will push an option to plot with MCMC and make that the default.
![image](https://user-images.githubusercontent.com/4108564/106994217-34b0ea00-6731-11eb-89bc-9ad088218997.png)

**Comment by andrew-edwards** [comment]
I just made it!

**Comment by andrew-edwards** [comment]
Said I was doing the figures with ** in captions, and this was the first one ;)

**Comment by andrew-edwards** [comment]
@kellijohnson-NOAA - no need to do the plot!

**Comment by andrew-edwards** [comment]
And I think the rest of the comments we've agreed before to not do. Could maybe right-align some columns in the two tables, but not a huge priority.
