### ISSUE TITLE
ADNUTS details

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#684]
The big things (such as use NUTS or not) will likely be in the SRG report. Be good to note some minor things here that would help us next year.
- [x] If using NUTS, do we need 2,000 samples or is 1,000 enough? I'm thinking that the document build might get slowed down a fair bit if every sensitivity run is MCMC. Andy: SRG is suggesting three MCMC runs, only the base model needs to be 2,000, age-1 index (and others if we do them) can be 1,000 for MCMC. 
- [x] similarly, reduce the number of sensitivity analyses to six or so Andy: kind of got reduced, they've been specific.
- [x] line numbers helpful on submitted version (preSRG version for reviewers, take them off for final version)?

**Comment by kellijohnson-NOAA** [comment]
On reducing the number of sensitivities - the Francis and McAllister-Ianelli ones could be removed because I don't think that they are helpful, especially the former because of its poor performance in the face of time-varying selectivity.

On the building of the document - I am guessing there are a few things we could do in the code to speed up the building of the document as well rather than just relying on not having a large number of samples.

On line numbers - I am more in favour of increasing the number of section/subsection headers rather than line numbers, line numbers are more of a copy-editor thing and are distracting in a finished document, imo.

**Comment by cgrandin** [comment]
Sensitivities - Yes I think we could drop some, for those parameters which have proved to be stable in this model configuration for the last 3-5 years.

The slowest part of building the document is the loading of all the RData files for the models at the beginning. The model objects carry around all inputs and outputs in both raw and processed form. This could be optimized down to only what we use. What we have is still faster than having functions read the SS input/output files in every time we want to make a plot though.

Line numbers - It doesn't matter to me either way. I agree that more sections would be beneficial because then we can refer to the TOC which in the PDF is clickable on the left side.

**Comment by aaronmberger-nwfsc** [comment]
Agree with all this.  Regarding adnuts posterior sample sizes, I think we let the model inform us what is enough given NUTS diagnostics.  The nice thing is that NUTS automatically thins at an appropriate rate, given how the model is performing, so X number of samples can be achieved for all MCMC runs even though the actual number of iterations may vary between them (if that makes sense).

**Comment by cgrandin** [comment]
@aaronmberger-nwfsc does that mean you can set how many samples you want returned for NUTS regardless of how long the chain is? I was under the impression the routine itself returned differing numbers of samples based on model parameter diversity.

**Comment by aaronmberger-nwfsc** [comment]
Yes, exactly.  You tell it that you want e.g., 2,000 samples and it will run and thin and etc. until it gets you the 2,000 posterior samples (or the 2,400 samples minus a warmup of 400 to get the 2,000) such that autocorrelation isn't an issue.  Well, in theory anyway, and with well specified models.  If this procedure doesn't work well it is not b/c of the algorithm but rather a poorly specified model.  The user specifies that, which is an advantage over other approaches. 

The above is my [admittedly limited] understanding of this.

**Comment by cgrandin** [comment]
Great - so given the code we present in the doc, I am trying to understand where the 7,850 samples comes from. I see *reps* which is the number of chains (cores to use) and *iter* which is set to 1,000. I don't see anything suggesting 7,850 samples for this case. Maybe this was because you didn't set that up and left it to the algorithm to decide?

```
library(adnuts)
library(snowfall)
library(rstan)
library(shinystan)
library(matrixcalc)
start_time <- Sys.time()

## Chains to run in parallel
reps <- parallel::detectCores() - 1
set.seed(352)
seeds <- sample(1:1e4, size = reps)
pth <- "."
exe <- "ss"
alg = "NUTS"
rdata_file <- "hake.Rdata"
system(paste0(exe, " -nox -iprint 200 -mcmc 15"))

## Then run parallel RWM chains as a first test to ensure
## mcmc itself is working properly, or that model is converging in mcmc space
thin <- 10
iter <- 100 * thin ## iter is per core
warmup <- iter / 4
inits <- NULL ## start chains from MLE
pilot <- sample_admb(model = exe,
                     iter = iter,
                     thin = thin,
                     seeds = seeds,
                     init = inits,
                     parallel = TRUE,
                     chains = reps,
                     warmup = warmup,
                     path = pth,
                     cores = reps,
                     algorithm = "RWM")
save.image(file = rdata_file)

##next check convergence and slow mixing parameters
mon <- monitor(pilot$samples,
               warmup = pilot$warmup,
               print = FALSE)
# max(mon[,'Rhat'])
# min(mon[,'n_eff'])@
slow <- names(sort(mon[,"n_eff"]))[1:8] ## Examine the slowest mixing parameters
pairs_admb(fit = pilot, pars = slow)
pairs_admb(fit = pilot, pars = c("MGparm[1]", "SR_parm[1]", "SR_parm[2]"))

## After regularizing run NUTS chains. First reoptimize to get the
## correct mass matrix for NUTS. Note the -hbf 1 argument. This is a
## technical requirement b/c NUTS uses a different set of bounding
## functions and thus the mass matrix will be different.
system(paste0(exe, " -hbf 1 -nox -iprint 200 -mcmc 15"))
save.image(file = rdata_file)

## Use default MLE covariance (mass matrix) and short parallel NUTS chains
## started from the MLE.
nuts.mle <-
  sample_admb(model = exe,
              iter = 500,
              init = NULL,
              algorithm = alg,
              seeds = seeds,
              parallel = TRUE,
              chains = reps,
              warmup = 100,
              path = pth,
              cores = reps,
              control = list(metric = "mle",
                             adapt_delta = 0.8))
save.image(file = rdata_file)

## Check for issues like slow mixing, divergences, max treedepths with
## ShinyStan and pairs_admb as above. Fix and rerun this part as needed.
#launch_shinyadmb(nuts.mle)

## Once acceptable, run again for inference using updated mass matrix. Increase
## adapt_delta toward 1 if you have divergences (runs will take longer).
mass <- nuts.mle$covar.est # note this is in unbounded parameter space
inits <- sample_inits(nuts.mle, reps) ## use inits from pilot run
## The following, nuts.updated, was used for inferences in this appendix
nuts.updated <-
  sample_admb(model = exe,
              iter = 1000,
              init = inits,
              algorithm = alg,
              seeds = seeds,
              parallel = TRUE,
              chains = reps,
              warmup = 250,
              path = pth,
              cores = reps,
              mceval = TRUE,
              control = list(metric = mass,
                             adapt_delta = 0.9))
save.image(file = rdata_file)
end_time <- Sys.time()
end_time - start_time

#launch_shinyadmb(nuts.updated) # evalute performance
```

**Comment by aaronmberger-nwfsc** [comment]
Good question:
I was under the impression it was (iteration - warmup) * number of cores.  So I was using 11 cores so it would be (1000-250) * 11 = 8,250.  Not 7,850...  I'll look into it more... but that's the idea

**Comment by aaronmberger-nwfsc** [comment]
I have an email out to Cole to help me understand this better.

**Comment by cgrandin** [comment]
I'm just thinking we may be asked to explore it a little during the meeting, e.g. producing 1,000 vs. 2,000 or more.

**Comment by aaronmberger-nwfsc** [comment]
Ok, here's what happened.  We should have got 8,250 samples (Cole confirms this) so my interpretation is correct.  However, we got 7,850 samples because I left the starter file at:

400 # MCeval burn interval
1 # MCeval thin interval

and it should have been changed to

0 # MCeval burn interval
1 # MCeval thin interval

So our run added a second 'burn in period' after the 11 individual chains were combined and thinned already themselves.  So NUTS gave us our thinned and ready to go for inference set of 8,250, but then SS further thinned that chain by ditching the first 400 to get the 7,850.  I don't think this affects any inference so we are fine, but just not a good (efficient) practice for future use.

**Comment by aaronmberger-nwfsc** [comment]
![image](https://user-images.githubusercontent.com/7946234/74963959-6cf7d500-53c7-11ea-92b8-9f035459c170.png)

This was even in his UW Think Tank presentation.....!

**Comment by cgrandin** [comment]
Ok, so you ran the MCMC on a 12-core machine? i.e. this code gives you 11:
 ```reps <- parallel::detetCores() - 1```
On mine it gives 7, so I would get ```7 * (1000 - 250)``` = 5,250 samples, not 8,250.

We need to make sure we all set **reps** to be the same in future (not linked to number of cores) if we are running models on different machines.

@andrew-edwards Do you think you could add a slide to the adnuts section in Sensitivities presentation with some info summarizing this?

**Comment by aaronmberger-nwfsc** [comment]
Yep you got it.  And one thing to note that we will never get exactly the same answer b/c of
seeds <- sample(1:1e4, size=reps)
However, the answers should converge to basically the same spot, despite different starting random seeds.

Also just noting an option Cole just sent me so adding his email response here:
[Yes, that would do it. I still 100% recommend letting adnuts do the thinning/burning, so yeah turn that off in the starter file.

BTW there is an option called 'duration' in adnuts that will stop the model after a certain time period. Can be useful if you want as many samples as possible in 2 hours. Specify a reasonable warmup value, then an Niter really big and then set duration to 120 (minutes). It'll automatically truncate all chains to the shortest one, but could be a useful option for you guys. ]

**Comment by aaronmberger-nwfsc** [comment]
Of course we could change that to a static vector of seeds if we needed to do so for exact repeatability....

**Comment by aaronmberger-nwfsc** [comment]
Sorry, one more thing - I just used Cole's 'standard' code so we can of course adapt it to work best for our workflow (e.g., random seed vector, sampling iterations, etc..).

**Comment by andrew-edwards** [comment]
Great. This is all why we're doing a test run this year, not using it for the main results! 

@kellijohnson-NOAA - I meant line numbers just for preSRG version (to help reviewers), take them off for final version (I wasn't clear originally, have updated my first post).

**Comment by andrew-edwards** [comment]
2021 - could each run the base model on own machine to then compare. Only need sensitivity models run once (on whoever's computer).

**Comment by aaronmberger-nwfsc** [comment]
Ok, I've uploaded some standard code to run adnuts on our base model and sensitivity models on our [drive](https://drive.google.com/drive/folders/16sEDTC4MNVwO8Z67t4_xZ_QfenlWivFH?usp=sharing).  This largely follows the code in our assessment document appendix from last year (with updates associated with the new version of adnuts).  As you will see, we will be using the development branch for this year given some recent additions that apply to using adnuts with SS.  Please note the comments at the top which will help us all get approximately 8,000 samples for each model we run despite our CPU configuration (# cores).  As I'm the least savvy coder on the JTC, comments are welcome for improving this run sequence.  Please check the box once you've downloaded the R script.

- [ ] Kelli
- [ ] Chris
- [ ] Andy
- [ ] Aaron


I'm currently running mcmc on our tentative base model (2021.00.04_base_v1) and will upload an mcmc subfolder when it is completed.

**Comment by cgrandin** [comment]
I added the code file to our repo so it's easier to find: b46d156a37b45b86ddec64f4b662b80f3138a3cd
Thanks @aaronmberger-nwfsc

**Comment by andrew-edwards** [comment]
I just added the calc for 7 cores in the code comments.
@aaronmberger-nwfsc  you said 978 iterations, and rounded this up to 1000 in the two `iter = 1000` situations, yes? 
Am thinking we should just create a variable `iterations` set to 1000 for 12 cores, 1400 for 8 cores (exact formula gives 1393), and use the formula for other values? Just to be safe and save changing for each person (and easier to understand in the future).

**Comment by aaronmberger-nwfsc** [comment]
Hmm, I guess I did do 1000 (even though I meant to change it to 978).  Using 978 I would have gotten a total of like 8,008 samples but instead I got 8,250.  At the end of the day it really shouldn't matter, but just for consistency lets shoot for something around 8,000 (be it 7,500 or 8,500 is fine).  So your 1400 with 7 (8-1) cores is perfect.  And yes we couldn't certainly set a target sample size and the variable reps is already your cores-1 so we could just solve (with rounding) for iterations automatically.

**Comment by aaronmberger-nwfsc** [comment]
Ok, I updated the adnuts-run-base-model.R file so that automatically does the number of iterations for you depending on the number of cores you have.  You should result with something very close to 8,000 samples when finished with mcmc (pending rounding to whole number of samples pending your # of cores).

**Comment by cgrandin** [comment]
Two questions for @aaronmberger-nwfsc :

- How is the MLE done? Is it done by manually by running SS on the command line?
- For the MCMC, did you copy the data files etc. into the mcmc folder of the base model and then run this code from inside that directory?

We can automate this whole process easily so that it runs everything from within the assessment framework (no moving files around, etc.) which would make it more secure and repeatable.

**Comment by cgrandin** [comment]
I added this commit 047315b24ead6c7d0f7188f866b6c4b9007fd181 which allows you to run the sensitivity by calling a function. It does it all automatically.

```
source("R/all.R")
source("R/run-adnuts.R")
run_adnuts('models/2021.00.30_noCohort_ageError') # Or whatever your directory is
```
This runs the MLE, creates the MCMC directory, copies all files to the MCMC directory, and runs the adnuts code.
I added batch files for my sensitivities which do this outside R so you can still use R, located in batch_scripts. 

The problem is see above, there was an error. There is an argument in the function called `check_issues` which can be set to TRUE to stop the function after the initial, short `sample_nuts` call. More investigation required but it is getting late.

**Comment by aaronmberger-nwfsc** [comment]
Regarding this comment (it showed up in my email notifications but I don't see it here):

[Two questions for @aaronmberger-nwfsc :

How is the MLE done? Is it done by manually by running SS on the command line?
For the MCMC, did you copy the data files etc. into the mcmc folder of the base model and then run this code from inside that directory?
We can automate this whole process easily so that it runs everything from within the assessment framework (no moving files around, etc.) which would make it more secure and repeatable.]

Yes, I am doing the MLE run first by running SS on the command line as we always have.
Yes, then I create a mcmc folder as you say and copy main model files over as you say.

As far as automating the whole process, I have stayed away from that for running models just so as to not get in the habitat of running a bunch of stuff without thoroughly investigating model performance (both MLE and mcmc) at each step along the way.  I think it is fine to do in general, but we just have to remember to not get complacent with too much automation and slack on due diligence (not that we would, just a precautionary tale....).

Nonetheless, your code here Chris will be helpful if you want to run a set of model overnight (e.g., at <2 hours each, one could run nearly 4 mcmc model runs while asleep!) - so much better than waiting 38 hours for one model run!

**Comment by cgrandin** [comment]
I deleted that comment because Infigured it out.. and wrote the automated function. I realize the issues with complacency in model runs but in this case if it’s just going through the motions I figured it was an easy thing to do. I’ve written another batch file which runs the other batch files sequentially so essentially just launch one process to run all sensitivities.

**Comment by cgrandin** [comment]
See 944dbd2fcf48f20cd5b563501dfae30370b3ecfe to auto-run batch scripts sequentially

**Comment by andrew-edwards** [comment]
Looks like Chris's function didn't do the shortened version anyway, yes Chris?

**Comment by andrew-edwards** [comment]
Regarding complacency and automation - given the .RData files are saved, we can still check the output after it's all run. And if things need changing then just re-run them. It does help understanding doing things manually, so maybe I'll do a couple manually. 

Definitely good that Aaron's done the base model more manually. Thanks all.

**Comment by cgrandin** [comment]
The function I made just runs everything in the section labelled:
# 2 shortened version for running sensitivity models (if fail, then may need to step through

**Comment by andrew-edwards** [comment]
Got the batch runs working. Had it all set up but it failed to find adnuts library. Figured out that my PATH still pointed to version 3.5.0 so had to change it to 4.0.2 (PATH doesn't seem to get updated when updating R), so just FYI in case you get the same issue. Now leaving it for a day to run....

**Comment by cgrandin** [comment]
I always change the install directory to C:/R when installing R so that my PATH never needs updating and so I don’t have multiple versions lying around.

**Comment by cgrandin** [comment]
The `mceval` argument doesn't seem to work in `sample_nuts()` so I had to run them all manually after the fact. I added the extra `system()` call to do it though, at the end of `run_adnuts()`.

**Comment by aaronmberger-nwfsc** [comment]
Did you update adnuts to the development branch?  Cole has fixed the -mceval not running issue in the dev branch.

**Comment by andrew-edwards** [comment]
Thanks both, that will explain why my .RData files are coming out smaller than using Aaron's manual method. Though I think my adnuts is the latest (<4 days ago). Just leaving it all running and will do `mceval` on Monday.

**Comment by kellijohnson-NOAA** [comment]
Thanks all for the work on this stuff. I found the issue extremely helpful and logic to follow regarding the progression. Yes, I agree with you Aaron regarding not running everything blindly, but I also like how Chris' function makes it where there are less places to make mistakes. I think that the function is the way to go here, but that the documentation in the function should explain how to look at the plots and such and which files you should open. Some comments on the run-adnuts
* snowfall::sfStop() should be added somewhere to run-adnuts because the parallel process is leaving stuff open in the directory. Is it bad to open and close these each call to run-adnuts? Should run-adnuts shut those off or should they be left open and then used again for each call to ad-nuts? I am not very well versed at parallel processes. Cole uses `on.exit(snowfall::sfStop())`. @cgrandin what do you think?
* Also, Chris ... can you use :: and ::: for non-exported functions so that I know where they are coming from? For example `tic()` could be `tictoc::tic()` which is helpful for me because I had no idea where the function was coming from. Thanks :)

**Comment by cgrandin** [comment]
**First point:** I don't have anything residual in the directories so I can't reproduce the problem. It works for me as-is. But if adding that line to the end of the function works for you by all means go ahead. And, yes in parallel computing the cluster should be stopped at the end of the run.

**Second point:** I'll explain why I don't do this anymore on Tuesday

**Comment by andrew-edwards** [comment]
@cgrandin Regarding the `mceval` command - you added after I set my simulations going, hence it didn't get used. I have the .RData files saved. What's the easiest way to run (rerun `nuts_updated()` with some options changed?). Thanks.

**Comment by andrew-edwards** [comment]
Actually, I'm just clicking on my existing `hake.RData` file then doing:
```
system("ss -mceval")
save.image(file = "hake.RData")
```
Should be fine yes? (As a one-off because the code changed).

**Comment by cgrandin** [comment]
Looks like we are all good on the adnuts runs for 2021
