### ISSUE TITLE
Assessment presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#688]
Some comments from me (overall looks great!):
- it might be worth (for future beamer builds - NOT this year) to separate out the SRG response questions to the appropriate presentations.  Most do relate to the assessment, but others might be better suited in other presentations (e.g., the ovary histological one and sampling protocol one and catch data extraction deadline one seem to fit well with the data presentation).
- first 'changes' slide second bullet: maybe just 'remove zero-sum recruitment deviation constraint ('simple' approach)' - not sure people will know what 'simple' means but I see we use it with figures so good to keep too but when in text throughout use quotes, i.e., 'simple'
- first 'changes' slide third bullet: technically we updated pre-2019 survey data too (a couple changes to CVs were made) - may not even be worth bringing it up, but just so aware
-second to last 'changes' slide fourth bullet: only one parameter, the survey theta, was stuck on the bound, so not 'these'
- it might be worth considering adding the prior figure that Ian sent us in issue 595 (https://github.com/pacific-hake/hake-assessment/issues/595#issue-550480621) just after talking about the prior (just after slide 13)
-second slide 'estimated quantities' last bullet: not sure what you mean by 'quite certainly'?  Do you mean the MLE and MCMC match up well?
-'estimates of 2014 and 2016 cohorts': the big change with the addition of the 2019 survey comps is the estimate of the 2017 year class (lower) relative to last years assessment (but not sure there is room on here for another comparison
- 'summary key cohorts': question will be what makes up the other 35% of biomass, so may want to include 2017 cohort , even if just in relation to the final three bullets about cohort % of population
- one key summary point might be one of caution:  we have the three highest catches in the last three years and the 2010 and 2014 large cohorts are now ageing (mortality outweighing growth) such that biomass is trending downwards (which will continue without either a reduction in catch/fishing mortality or another big recruitment and no evidence that recent recruitments will be a boomer.  I'll get into this a bit more in the management talk, but seems like a summary of the assessment results in terms of current status. (sure we are trending toward the 'target' but we don't want to overshoot!)

**Comment by cgrandin** [comment]
@aaronmberger-nwfsc Thanks for taking a look. I agree with emphasizing the current state of high catch and no large incoming recruitments, so I'll add that to the summary. I'll also add Ian's figures for the DM stuff (I had forgotten about that figure). 

For the % biomass by cohort I may make a whole slide which has them all for reference. Then there's no question what's going on.

I'll work on this today and possibly into tomorrow.

**Comment by aaronmberger-nwfsc** [comment]
Thanks Chris and sorry for the late comments!  Please wait until tomorrow to work on any changes as none are crucial and the presentation is great even if you didn't get to any of them.  :)

**Comment by kellijohnson-NOAA** [comment]
Nice job, this is a long one. I really like how you put the document figure reference at the top of the slide. Also, feel free to ignore the following comments as they are trivial.
- Could add last year's weight-at-age figure before slide 8 to allow people to flip between them
- Switch slides 10 and 11
- Slide 13, I believe it was just the survey weighting parameter that was hitting the bound not both
- Slide 35 - remove "So "
- Slide 60 the passive voice is quite strong here and I had to re-read "have been dropping since" a few times to get it, sorry my brain is slow :(

**Comment by cgrandin** [comment]
Given the high interest in cohort strength on the JMC call (and the subsequent Canadian JMC call) I added a slide which gives an overview of the cohort biomass estimates with uncertainty for the terminal year. The table is sorted by cohort strength.

It used the posteriors in ```base.model$extra.mcmc$natselwt.prop```

Does this seem like a good addition? If so, I want to make sure I understand the values in that output. My interpretation is that they are proportions of biomass with selectivity applied, which is why they only sum to 96.1%. Is that right? (@aaronmberger-nwfsc, @kellijohnson-NOAA)

![image](https://user-images.githubusercontent.com/4551051/75126122-5e324c00-566d-11ea-9960-f1f268107467.png)
Thx

**Comment by kellijohnson-NOAA** [comment]
I like the plot, not so sure if you need the plot and the table, though as @andrew-edwards mentioned it is better to present information in multiple ways. Regarding the values not adding to 100%, I am almost certain that is because there is no constraint that the median for each age will come from the same row, where all rows will sum to one.

**Comment by aaronmberger-nwfsc** [comment]
Yes, that makes sense to me and I like the plot.  I think we get the same thing with selectivity (or any sum to one set of proportions for that matter) when summarizing values from posterior draws.  I was a bit surprised that it was that far off ~4%, but shape of posterior and summarizing metric (median, mean, etc.) would influence this I would think.  I wouldn't even mention that they don't sum to one, but have that explanation ready in case someone asks.
