### ISSUE TITLE
Management presentation

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#690]
Just adding this in here for completeness - if anyone has time to have a look and has any comments/suggestions I'll have time on Monday evening to work on additions/subtractions.

**Comment by cgrandin** [comment]
Looks really great @aaronmberger-nwfsc. I checked all the values, which seem to be correct.

Here are a couple comments:

Slide 9 - Third point "Median (50%) decreases **_from_** 2021 **_to_** 2022 ...
            - Option "d" (410,000) isn't in the table but it is an important value, maybe replace "c" with "d" in table (If you want to do this and need help with it let me know I don't think it's trivial)

Slide 10 - The cohort % by weight values do not match with what I have in the Assessment presentation. The numbers in this one seem to be from the ```base.model$extra.mcmc$natselwt.prop``` and in assessment one are from ```model$natage``` and ```model$wtatage```. I think the numbers here are correct and the ones I have used are from the MLE. I will change mine unless there is something I'm missing.

Slide 16 - This is great as I have the upper left portion of this plot in the Assessment pres.

Slide 19 - It would be easy to add the small decision table for the age-1 index case in a slide after slide 19. Slide 20 (and 22 for adnuts) references a lot of these numbers and it may be easier just to see the table. Or possibly - have three slides AFTER the ending slide with the three decision tables: base, adnuts, and age-1. @kellijohnson-NOAA I know we shouldn't be using results for choosing a model right...

**Comment by kellijohnson-NOAA** [comment]
Great! Below are some minor comments, feel free to ignore them all

Slide 2 - The colours aren't labelled, so they are not very helpful; the y-axis label should be specific to something and not just a unit, e.g., 'Catch or TAC (1,000 t)' to match the next slide; switch bullet points under March 2019 to match the order that they happened in time
Slide 3 - Can the middle entry of the legend be changed to "Management TAC"?
Slide 4 - The y-axis label doesn't fit
Slide 5 - Change "Average" to "Mean of" to match second bullet point and the main text
Slide 6 - The units in the x-axis are labelled differently than the other slides, can we stick with (1,000 t); change "Harvest rule" to "Harvest-rule" in title
Slide 7 - Third bullet point, can we just shorten to "Uncertainty is large" because in theory it wouldn't increase indefinitely. 
Slide 8 - Why are some of the catch streams gray? Nothing needs to be changed I am just curious
Slide 9 - Make the last bullet two shorter bullets, i.e., 
```
* Median > B_40% for all 2021 catch
* Median < B_40% for e and h
```
Slide 10 - Change "fishing based" to "fishing-based"; capitalize tables and figures
Slide 12 - x-axis label
Slide 15 - it isn't clear which catch scenario this is from
Slide 16 - extra parentheses by 0.91; add comma after 0.91
Slide 17 - It isn't clear what is meant in the last bullet point with 1-2%, do you mean 1-2% lower or 1-2% were caught?
Slide 18 - Remove "high (" and ")" to just state the probability
Slide 20 - Change the first bullet to have age-1 results first, which matches the other bullet points
Slide 21 - There should be an explanation of what the "red" colouration means for those that are looking at the slides later but not in the room
Slide 22 - Change the first bullet to have age-1 results first, which matches the other bullet points

**Comment by aaronmberger-nwfsc** [comment]
Thanks for these comments - I'll be traveling (driving so can't work) most of the day today, but will have time tonight to work on these.  I'm hopeful to get to them all.

**Comment by aaronmberger-nwfsc** [comment]
Chris:
Regarding comment: "Slide 10 - The cohort % by weight values do not match with what I have in the Assessment presentation. The numbers in this one seem to be from the base.model$extra.mcmc$natselwt.prop and in assessment one are from model$natage and model$wtatage. I think the numbers here are correct and the ones I have used are from the MLE. I will change mine unless there is something I'm missing."

Isn't the assessment presentation showing the proportion by cohort in the population, where slide 15 in the management presentation is talking about proportion by cohort in the catch.

**Comment by cgrandin** [comment]
Is that what ```base.model$extra.mcmc$natselwt.prop``` is representing? I was under the impression that this was the estimated 2020 numbers-at-age * wt-at-age * selectivity in MCMC context (posteriors). I didn't think it represented anything to do with catch but if it did please let me know so I can fix the presentation. Thx

**Comment by aaronmberger-nwfsc** [comment]
I have yet to look deep into this but if it is 2020 numbers-at-age * wt-at-age * selectivity in MCMC context then it is estimating the proportions in weight available to the fishery (a.k.a. vulnerable biomass or proportions that can be caught.  This is different than just 2020 numbers-at-age * wt-at-age which is the proportions in weight in the population.  Perhaps we are talking about the same thing.  
The management presentation slide 15 is showing the base.model output for forecasts using the default harvest control rule catch levels with forecast selectivity applied.
The assessment presentation slide 60 I thought was just from the population, not the vulnerable biomass (i.e., adjusting for selectivity).  Is that correct?

**Comment by cgrandin** [comment]
Oh man if that's what those are then I have to take that slide out of the assessment presentation, or you can put it it the management presentation after slide 15 if you want. It is using those same values.

**Comment by cgrandin** [comment]
OK, I removed this slide from the assessment talk and added it to the management talk after slide 15 (numbers match). @aaronmberger-nwfsc feel free to comment it out of your talk if you don't want to show it. It won't bother me if you remove it.
