### ISSUE TITLE
ADMB recdev issue

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#701]
See #590 which explains it and the ADMB issue: admb-project/admb#107

**Comment by kellijohnson-NOAA** [comment]
Do we need to explain the non-zero sum simple dev approach more in the document? I think that they asked for this in passing but did not formally document it as a request.

**Comment by aaronmberger-nwfsc** [comment]
I don't recall any specifics that were said.  I feel like we give it adequate treatment in the bridging section, but it may be beneficial to beef it up.  I could go either way on this one.

**Comment by andrew-edwards** [comment]
2021?

**Comment by cgrandin** [comment]
I recall them (especially Trevor) asking for a more thorough write-up of it which is why I started this issue, linking the info in one place

**Comment by andrew-edwards** [comment]
Given it wasn't a formal request I say we do it for next year ;)  Be good to get submitted soon.

**Comment by aaronmberger-nwfsc** [comment]
As we don't refer to the rec dev issue really at all in this assessment, @kellijohnson-NOAA and I were thinking that there was no reason to add text to the document itself.  However, it would be good to eventually add an explanation here so that we don't forget details.  I'm earmarking this for the 2022 assessment, but we really should make some notes here before next year (not today though!).

**Comment by cgrandin** [comment]
I opened this because I was left not fully understanding it, but it can wait until 2022...

**Comment by kellijohnson-NOAA** [comment]
Reference the publication that will come out from the Stock Synthesis team.

**Comment by kellijohnson-NOAA** [comment]
Problems with the sum to zero constraint wrt Bayesian inference and stan is talked about [here on a google group for stan-users](https://groups.google.com/g/stan-users/c/LPgyXCRZ8ys/m/bgZlXFpnAwAJ).

**Comment by aaronmberger-nwfsc** [comment]
Is the main issue described by the post (wrt sum to zero constraint):
[It is something people did in WinBUGS, but it's going to
be a problem in Stan because the posterior over the parameters
(that is, what's defined in the parameters block) isn't proper.
In particular, the no-U-turn sampler won't make U-turns --- it'll
just keep running.]

**Comment by kellijohnson-NOAA** [comment]
I think so.

**Comment by kellijohnson-NOAA** [comment]
Lots more discussion on this topic [here](https://groups.google.com/a/admb-project.org/g/users/c/63YJmYGEPuE) in google groups. Essentially, the sum to zero constraint should **NOT** be used in an MCMC context no matter what.
