### ISSUE TITLE
Run lengths of base model

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#702]
In bridging of 2021 the base model should be run with more samples using Metropolis algorithm and NUTS to ensure that both models are converged when comparing them.

**Comment by andrew-edwards** [comment]
And I think also rerunning the 2020 model, since we can re-run when we have time before we get swamped. And it should get at the same understanding, hopefully.

**Comment by cgrandin** [comment]
NUTS had 7000 and the base MH had 2000. SRG wanted us to run the base longer to show that the convergence diagnostics are similar.

**Comment by andrew-edwards** [comment]
Run base MH longer so that Figure A.4 (p156) looks closer to Figure H.17 (p221).

**Comment by aaronmberger-nwfsc** [comment]
I've started a longer Metropolis Hastings mcmc run (i.e., not using adnuts package) to more similarly match the number of samples produced using adnuts and last years base model (so shooting for ~ 7,000 samples rather then the normal 2,000 from our previous MH procedures).  As such, I'm running a 74,000,000 chain with samples at 10,000 intervals and removing the first 400 samples for burn in.  This will take about 38 hours (= 2,000 samples) * 3.5 or close to one week of run time on my remote desktop.  I'll look at diagnostics when done, compare, and then report here.

**Comment by aaronmberger-nwfsc** [comment]
After restarting (continuing) the chain five times due to remote desktop shutdowns, etc, this is finally done.  A lot of computing time for 0 gain.  The diagnostics look essentially exactly the same for this run (10,000 samples) versus last years base model (2000 samples).  Recall that I used last years base model for this test.  The main difference between last years Metropolis Hastings run and the NUTs run was the estimate of R0 (slightly different, ~9% decrease).  This test using a longer MH run resulted in essentially the same estimate of R0 as last year, so no new differences there.  It seems like the difference here might be in the actual sampling approach between MH and NUTS for sparse parameters like R0.  I'll look into the literature to see if I can find anything on advantages/disadvantages of NUTs from a theoretical or first principles basis.  From my understanding it is an improved approach so it should just be better - that is that.    The below is the 4 panel diagnostic plot from the 10,000 sample MH run.  When compared with last years figure (Figure A.4), you will see almost no difference.
[SummaryDiagnostics.pdf](https://github.com/pacific-hake/hake-assessment/files/5869786/SummaryDiagnostics.pdf)

**Comment by cgrandin** [comment]
Great. Thanks for taking the time to run it. I think it is pretty close to identical. Are we going to include this in the assessment document? Or keep it for back-pocket/presentation only?

**Comment by aaronmberger-nwfsc** [comment]
Not in the assessment document, just back-pocket stuff in my mind...

**Comment by cgrandin** [comment]
I think we have agreed on everything about run lengths, at least I hope so with only 10 days left.
