### ISSUE TITLE
JMC presentation for 2020

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#706]
@aaronmberger-nwfsc  - It's looking good so far.

- Should we possibly move the "Age-1 index: correlation with base recruitment estimates", and two TAC slides so that the phase plots for this year and last year are together? It could possibly be handy to switch between them.

- Moving the legend in the risk plot for 2020 catch. I will try to move it down into the middle so we can see the top black line

- Paul R. has asked to see the cohort table (Table 24) with 2016 and 2017 cohorts added. We added 2016 after submission so it's already in there but do you see any benefit to showing 2017? Currently the slide only has 1999, 2010, and 2014. We can split them up to make two slides so they all fit.

**Comment by aaronmberger-nwfsc** [comment]
Sure, let's end the Model Estimates section with the current phase plot and then start the Past Management section with the previous phase plot. (good idea)

Sure, give the legend movement a try - I'm not overly worried about that - you can still clearly see and read everything...

Sure, let's leave the current one as is (includes 1999, 2010, and 2014) and then make another slide that follows showing 2016 and 2017 - just because it was asked for.  We will have to again reiterate the uncertainty, especially in 2017, but it okay to show in my mind given the survey has now seen both once and survey age comps match fishery age comps pretty well.  Are you going to add this stuff?

I also would like to add a few more bullets in terms of the summary slide - just highlighting why the stock is declining (i.e., 3-years of record high catches, no dominant recent year class, and recent decline in 'surviving biomass' (cohort tables) of large 2010 and 2014 year classes) - just to drive home that 'we' should be a bit more cautious this year then in past recent years, despite trending towards the 'target' we don't want to rapidly overshoot it!

**Comment by cgrandin** [comment]
I'll do all these additions, if you can track down Ian's code (it's somewhere in an issue on here) on the 'actual models used' squid plot and try to get it working. I also don't think it is necessarily that useful as the model structures are different - also I won't have the folder structure so I think in this case a one-off as a picture would be ok to add.

**Comment by aaronmberger-nwfsc** [comment]
I had forgotten that Ian already created this plot???  You remember that he did?  If so, then I'll look it up and have a look and/or email Ian directly (he's good at organization and will likely have it if we can't find it herein).

**Comment by cgrandin** [comment]
I'll try and find it

**Comment by aaronmberger-nwfsc** [comment]
Okay, how about you add these and then I can have a look and add that final summary bullet points, ok?

**Comment by cgrandin** [comment]
About the phase plots.. I am wondering if this is really true (third point):

**When biomass goes below target, fishing intensity typically decreases**

**Comment by aaronmberger-nwfsc** [comment]
Yea, I thought the same thing when putting that together.  I think it does if you squint and look beyond 1-2 years post going below, but even then the answer is 'kinda'.  Let's remove that bullet as I don't think it is very useful.  We could instead add something about where we are now (2020) as the other two bullets are more general.  Maybe we add the joint probability calculation of both overfishing and overfished occurring just to show that it is small.

**Comment by aaronmberger-nwfsc** [comment]
Could report current B2020/B0 number and the current rel fish intensity number and then the joint probability number.

**Comment by cgrandin** [comment]
That's a good idea. I will do that.
