### ISSUE TITLE
Running standard set of sensitivity models with mcmc - assignments made!

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#717]
I think we are ready to run our standard set of sensitivity models with mcmc, and as such let's divide and conquer.  So you should start by downloading the existing bridging models on the google drive (just to have in general) and especially 2021.00.04_base_v1.  This base_v1 model is the one that we will make changes to for each respective one-off sensitivity. 

Download bridging models and base_v1 model
 - [x] - Aaron
 - [x] - Kelli
 - [x] - Chris
 - [x] - Andy

Next, have a look at our model readme [file ](https://docs.google.com/spreadsheets/d/135Ba1I4s_rp9oZznz57sbxM1hcT6KwER4wSyINQH4nI/edit#gid=2131798231)on the google drive and find your assigned sensitivity runs to do by following the adnuts run [code](https://github.com/pacific-hake/hake-assessment/blob/master/R/adnuts-run-base-model.R).  Let me know if you have any questions on how to run adnuts or how to structure .dat and/or .ctl files for any specific sensitivity.

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards the h sensitivity has always run h=1 with an upper bound of 1.0. I think this leads to poor convergence given the parameter is on the bound even though it is a fixed parameter. I think we should explore using h = 0.97 or something that is a little bit less than h=1 give the upper bound cannot go above one.

**Comment by kellijohnson-NOAA** [comment]
Anyone remember the context behind the sensitivity that removes the survey? The model does not converge if you actually remove everything, only if you turn the likelihood off.

**Comment by cgrandin** [comment]
There are a bunch of changes in the control file for this sensitivity when compared to last year's base model (I just did a diff) and it looks like various parameter initial values were modified and a bunch of other things. I have no recollection of these changes so it was probably @aaronmberger-nwfsc that made them.

**Comment by andrew-edwards** [comment]
Note that the README_2019 file has details of exactly what needs to be changed for each sensitivity run (since during shutdown Chris and I had to figure it out by diff-ing the 2018 runs to the 2018 base model). I used the README to check what to change this time (since only use SS for hake so have to remind myself!).

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards can you point me to a commit or link to line number, I don't see what you are talking about. Also, the removing the survey sensitivity run hasn't been around for forever. I am trying to remind myself why we are doing it and who asked, not necessarily how.

**Comment by aaronmberger-nwfsc** [comment]
The no survey run was a side run last year by Kelli and myself after discussions with the joint survey team about the importance/effect of the survey.  We do not need to do this one again, unless someone is simply curious.

**Comment by andrew-edwards** [comment]
@kellijohnson-NOAA  I was referring to the README_2019 on the Google Drive (the spreadsheet listing all the runs), but didn't post the link here as here is public!

But, you're right - the survey sensititivy hasn't been around forever - wasn't actually in the 2019 sensitivity set (so the README_2019 is no use). Sorry, I hadn't checked, and was just responding to Chris's comment about diff'ing the files (since that's all documented for 2019). 

It wasn't actually in last year's document. Oh, think Aaron just said why it's there.

**Comment by andrew-edwards** [comment]
Also the Hamel M prior (run 22) was run last year but not in the document. I ran it anyway (and see Chris added it into the build), but we can probably leave it out again after taking a look.

**Comment by aaronmberger-nwfsc** [comment]
Let’s discuss tomorrow the inclusion (or not) of the Hamel prior run.

**Comment by andrew-edwards** [comment]
Sens models all assigned and run. Hamel prior is in the doc build, so we can take a look at the figures. Closing this.
