### ISSUE TITLE
Table 11 goes past the page lines

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#727]
Table 11 has too many rows. The caption can be shorted to reference the document section that explains how age-comps are created even more than previously done, the colname of Number of samples could be reduced to "N" and add (N) to the caption, and the ages could be used as column names rather than having two lines.

**Comment by cgrandin** [comment]
You can also make it a smaller font

**Comment by andrew-edwards** [comment]
'No. samples' might fit on one row.
Also, similarly, several sideways tables (Tables (20, 21, 22) need tweaking/fixing to avoid blank pages. Happens every year (so maybe search past Issues).

**Comment by andrew-edwards** [comment]
Looks like (Figure 19 of compositions of median fits to age comps) that we do have medians of proportions-at-age, so maybe we can update Tables 20-22 to be MCMC?

**Comment by cgrandin** [comment]
@andrew-edwards I made a commit which makes this table multiple landscape pages, and a little larger font. The problem is that the second landscape page has a footer on the side. I noticed that the other landscape pages have no footer at all. I wondered if you wanted to take a crack at trying to resolve the footer issue which is a LaTeX issue? I have tried in the past with csasdown but couldn't get it right.

![image](https://user-images.githubusercontent.com/4551051/105394848-ef3dda00-5bd2-11eb-85f1-8888849f2a39.png)

**Comment by andrew-edwards** [comment]
I'll look into it at some point. Don't expect it will be fun ;) 
Yes, we can't keep getting away with just shrinking fonts, so need multi-page landscape tables. My current build has the blank pages between landscape tables, which I think is related (and they got a row longer than last year, pushing something over the edge....).

**Comment by cgrandin** [comment]
I actually made some progress on this because the whole doc was messed up. See a6d391f35d71eee0f4bfb608240f6a8838a8f3a1

The only remaining issue here is that the page number does not appear on the second landscape page of a **longtable**.

This will allow us in the future to make all the large, landscape tables **longtables** instead of just making the font smaller every year to try and squeeze it all on one page!

**Comment by cgrandin** [comment]
Major changes fixes this: 5dddb53b0268e7a5a8bef079b2d423cd35b9d221
