### ISSUE TITLE
Web accessibility requests Jan 22, 2021

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#740]
There are a couple of requests in addition to what we have done:

- Tag the  "One page Summary", "Executive Summary" as Header 1 (instead of starting at Heading 3), and then subsequent headers as 2, 3, etc.   
-  Provide tooltips (alt text) as a separate document, in the event the need arises to manually copy and paste them into the alt text fields in the tags  
 
Also, if possible, web folks would like to take a look at a larger version closer to the final document just to get a better sense of what issues will need to be addressed before posting, and how often they occur.

**Comment by andrew-edwards** [comment]
Point 2 - maybe we should clarify if that need really will arise (rather than 'just in case'). Maybe we can extract the text automatically from the final hake-assessment.tex. But someone manually copying and pasting seems to defeat the point a bit. 

When we send them a larger version then maybe we ask if they really need the second point, once they've seen it all.

**Comment by cgrandin** [comment]
Number 2 is fairly easy, I'll just have it write out a file when it's reading the alt text in during the build process.

**Comment by andrew-edwards** [comment]
Nicely done. Did you fix the Header tags also (I can't seem to check on .pdf)? I remember that being a pain for CSAS documents.
