### ISSUE TITLE
Disconnect between forecast plots/tables

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#747]
Looking at the no fishing forecast in figure i (similarly figure 35; blue line) it seems like there would be an "on average" chance that the stock would increase going from 2021 to 2022 and an even higher "on average" chance that it increases again from 2022 to 2023.  However our probability tables (i and j in the ex summary) show at 65% chance of decreasing from 2021 to 2022 and a 52% chance of decreasing from 2022 to 2023 with no fishing (i.e., 0 catch).  Is there a median versus mean difference here or something different going on?

**Comment by andrew-edwards** [comment]
So, after going down a rabbit hole into SSplot functions (in case it was plotting the mean), I think the figure is correct and is showing the medians (we should state this in the caption) and the correct credible intervals.

So the confusing aspect is that (for 0 catch) as Aaron said:
```
Prob(B_2022 < B_2021) = 65%   # yet median only slightly down
Prob(B_2023 < B_2022) = 52%   # yet median increases
```
which seems counterintuitive.

The figure is for relative biomass, but that's not the issue, since
```
Prob(B_2022/B0 < B_2021/B0) = Prob(B_2022 < B_2021)
```
as B0 is the same for each MCMC samples (and these probs are calculated by counting the proportion of samples for which the inequality is true).

I think I'll do a plot with a line for each MCMC (like `make.selex.uncertainty.lines.plot()` for Figure 23). I think it must be that
the lines in such a plot will cross over each other (like in Figure 23), whereas we kind of intuitively think of them as not overlapping. If not overlapping then the median would correspond to a particular MCMC sample, and it would seem highly
unlikely that the current situation could occur (65% go down yet the middle one only goes down slightly). So I think they must overlap more than we'd expect. 

Also, a lot of them might only go down a very tiny amount (and so all contribute to the 65%), but that wouldn't affect the median. That might be more the issue.

To be continued, as I think it's worth fully understanding.....

**Comment by cgrandin** [comment]
I think the second table is wrong. It looks like it should be 84%, not 52%

**Comment by cgrandin** [comment]
Thanks Andy. I also checked the plot code and the code that makes the tables as well and they look accurate. It looks like the posteriors are increasingly biased low (left of the median) as the forecasts go forward in time. 

![image](https://user-images.githubusercontent.com/4551051/106206338-bb375b80-6174-11eb-9e4b-effef62e9130.png)

![image](https://user-images.githubusercontent.com/4551051/106206406-ddc97480-6174-11eb-96a4-e6d1d6e9d172.png)

![image](https://user-images.githubusercontent.com/4551051/106207242-4533f400-6176-11eb-97c5-9acb64052843.png)

**Comment by andrew-edwards** [comment]
What's wrong with this? Why am I getting 90% of MCMC samples for which biomass in 2022 is smaller than 2021; should be 65% (as per Aaron's question):
```
dat <- base.model$mcmc[, c("SSB_2020", "SSB_2021", "SSB_2022", "SSB_2023")]
decrease <- dat$SSB_2022 < dat$SSB_2021     # TRUE if decreases
sum(decrease)/length(decrease)
# 0.8985455
```

**Comment by cgrandin** [comment]
Because the table code is using this:

```
x <- base.model$forecasts$`2021`$`01-0`$outputs$SSB_2022 < base.model$forecasts$`2021`$`01-0`$outputs$SSB_2021
```
You are looking at the "forecasted during main run" forecasts which are incorrect

**Comment by cgrandin** [comment]
That said, all those density plots above are wrong because I used the code you did :(

**Comment by andrew-edwards** [comment]
Here's a plot of 1000 of the MCMC samples. Something not quite right with the relative number of blue versus pink lines (see previous question), but it's interesting. Shows the general decrease in the posterior as time goes forward, as shown in Chris's plots (thanks for those). But also shows how most of the tail is pink (increase from 2021 to 2022). 

Just saw Chris's post - thanks I'll update my figure. That explains why it's wrong.
![depletion-trace](https://user-images.githubusercontent.com/6977190/106208121-ba53f900-6177-11eb-8f52-892f776f1779.png)

**Comment by andrew-edwards** [comment]
I thought your medians between the first two should be closer.
Here's the correct plot, giving the 35%/65%:
![depletion-trace](https://user-images.githubusercontent.com/6977190/106208520-5ed63b00-6178-11eb-86d0-26aa77b4833f.png)

**Comment by aaronmberger-nwfsc** [comment]
And I suppose, we are not just tracking variability in the posterior (or central tendency via median or mean) for SSB in forecast years but also paired variability for the equilibrium SSB0, given we are looking at relative SSB in figure i.  Whereas the text is related to going 65% (2022)and 52% (2023) just with SSB (not relative SSB).

**Comment by andrew-edwards** [comment]
So it looks like the 35% reds increase more than the 65% blues decrease (they gradually decline), pulling the median up.

**Comment by andrew-edwards** [comment]
@aaronmberger-nwfsc  - I don't think that's it. See second part of my first comment. SSB0 is the same within a sample.

**Comment by andrew-edwards** [comment]
I thought there'd be some difference the red sample parameter values and the blue sample ones. But M, R0 and h all look similar. So the red ones aren't increasing because they're inherently more productive.

**Comment by kellijohnson-NOAA** [comment]
@andrew-edwards is it really fair to base "increasing" off of a single year? I would think that a lot of it has to do with the recruitment deviate rather than biology b/c of the short-term forecast or am I missing the point?

**Comment by andrew-edwards** [comment]
@kellijohnson-NOAA - yes, could be to do with recruitment deviates (in the past). You're the biologist around here, but I thought I'd give the biology answer a stab ;)

**Comment by andrew-edwards** [comment]
Here's a histogram of relative biomass in 2022 minus that in 2021. Red are again MCMC samples that increased from 2021 to 2022 (so positive values in the histogram) and blue are decreases (and so negative). Shows a bit more clearly than the trace plot how the blue decreases are all small, but some red increases can be large.

Also, see the printed text values in the figure: 
1. Median in 2022 minus median in 2021 is -0.004. That's the difference in the medians. Slight decline, which explains the blue line going down in Figure i.
2. Median of (relative biomass in 2022 minus that in 2021) is -0.028. That's the median of the differences. Showing that it doesn't have to be the same as the -0.004. The median difference is -0.028, but that's not what's shown in Fig i.

So, to answer the question (and summarise in case anyone asks): 

The median relative biomass in 2022 is slightly lower than in 2021 (Figure i), but so close that, yes, you would think there is a 50:50 chance of going up or down. However, that's the difference in the medians. 

The probability of a decrease is 65%, which is the proportion of MCMC samples that decrease between 2021 and 2022, which is 634/1000 (not quite 65% since I'm doing a subsample for the histogram).  

One final calculation which actually explains it I think - the median difference is -0.028, and there are 13.4% of subsamples that have difference > -0.028 and  < 0. So that gives the roughly 15% discrepancy in Aaron's question, being how often difference between years is bigger than the median difference (-0.028), but still show a decline (difference is < 0). These are the samples in the histogram between the vertical magenta line and a vertical line at 0. 

I'm putting the code at the end of `figures-mcmc-diagnostics.R`, but commented out, so it's there for the future.
![depletion-histogram](https://user-images.githubusercontent.com/6977190/106536666-c7415700-64ad-11eb-85fb-f3e2514201ff.png)
