### ISSUE TITLE
Retrospective MCMC squid plots done - You need to update r4ss 

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#760]
Done here: 7f1f1d3bb3d437f2a700df3b2fbe3ea64f7b42ab
I had to fix `r4ss` here: https://github.com/pacific-hake/hake-assessment/commit/7f1f1d3bb3d437f2a700df3b2fbe3ea64f7b42ab

Note that change is on my fork of `r4ss` so you'll have to pull from there: https://github.com/cgrandin/r4ss/tree/bioscale
I think the command is `remotes::install_github("cgrandin/r4ss", ref = "bioscale")`

- [x] Kelli
- [x] Andy
- [x] Aaron
- [x] Chris

@kellijohnson-NOAA - If/when you want to include this in the official `r4ss` code, let me know and I will send a pull request.

The cohort recdevs in the MCMC version appear to stabilize a year sooner than in the MLE version..

Here is the MCMC version:
![image](https://user-images.githubusercontent.com/4551051/106590590-1e711700-6502-11eb-832a-2de2faf0713b.png)

And the MLE version:
![image](https://user-images.githubusercontent.com/4551051/106590660-334daa80-6502-11eb-84eb-aef904786f61.png)

**Comment by kellijohnson-NOAA** [comment]
Thanks @cgrandin. I am looking now at merging it in, which I can do without a pull request. Just trying to think about the repercussions of renaming main recruitment deviations to late deviations. Also, for the squid plot ... should we subset the mcmc differently rather than renaming? Seems like it would be better to just find the years rather than if they are labelled main or late.

**Comment by cgrandin** [comment]
@kellijohnson-NOAA by all means if you can get that to work go ahead. I was trying to leave as much as possible the r4ss code as it was. I doubt anyone else is using the retrospectives with MCMC so my thought is that the SSplotRetroRecruit function changes would be fine. I was more worried about changes to SSsummarize.

**Comment by cgrandin** [comment]
I can actually take another look in a bit if you have other stuff to do, now that you mention that it may be a better way.

**Comment by kellijohnson-NOAA** [comment]
I am in it right now. merge.duplicates is used for more than the recruitments, so I am just trying to think of a way that doesn't break people's code. Also, names might be different based on how you ordered your models in the list b/c the modification takes the name from the first element. Right now, the code works, so we can just roll with it; I will just needs to think of how to best modify it for ALL models going forward is all.

**Comment by kellijohnson-NOAA** [comment]
BTW thanks for using :: :)

**Comment by cgrandin** [comment]
That was where I knew you might have a better idea. You could just have two merge functions, one for recruitments and the original ones for the others. Then just change the call to it at the end of the Sssummarize function. I knew you’d like the ::

**Comment by kellijohnson-NOAA** [comment]
What about tidyr::separate? And we can drop the stuff before the first "_", then downstream greps would still work I think.

**Comment by cgrandin** [comment]
Sure, that’s worth a try. I didn’t know about tidyr::separate, looks useful

**Comment by cgrandin** [comment]
You can also use mutate(x = sub())

**Comment by kellijohnson-NOAA** [comment]
* late-period years without data and forecast period recruitment deviations
  * In MLE mode are 0.0 unless they are set to be the mean of a period, which is a new feature in SS that we are not using. 
  * Any late-period year without data (2020 for the 2021 because there are no age-0 age data) or forecast-period year have a recruitment deviation of zero in MLE.
* MLE bias adjustment to adjust recruitment deviations to be mean unbiased
  * MCMC can fully explore the lognormal domain of each recruitment deviation and doesn't need bias adjustment, thus there is estimated uncertainty or recruitment deviations in this period.
  * MLE recruitment deviations are penalized towards zero, thus for years with no information in the data, these will be overly penalized and the mean will be smaller than it should be.
  * Calculations based on median or geometric mean recruitment will underestimate mean biomass because the expected arithmetic mean depends on the geometric mean and the variability of the lognormal distribution. 
  * In the ramp down, i.e., last_yr_full to first_recent_yr_nobias, there will be a small bias adjustment applied to the recruitment deviation which penalizes it towards zero; sometimes this penalty will make it where the recruitment is not large enough to remove catches.
* Positive recruitments in forecast period are often a result of the model needing enough biomass to support catches. 

Does anyone think that I should put a sentence in the document or just leave it as is? I tried to find a good place to put it, but there is only half of a sentence in the main text that actually references this figure.

**Comment by aaronmberger-nwfsc** [comment]
This is interesting; and wrt the MCMC and fully exploring the lognormal domain of each recruitment deviation statement - I think that help me explain our observations for #747.  I think basically we just need to explain it.  If we were going to put it somewhere maybe a sentence in the figure caption (????) explaining the phenomenon.

**Comment by andrew-edwards** [comment]
Good sleuthing Kelli! Maybe worth mentioning somewhere (yes, maybe just in caption) if you like.

**Comment by cgrandin** [comment]
Great description @kellijohnson-NOAA. I think that since we are no longer using MLE and the MCMC fully explores the domain of the deviations we don't need an explanation in the document. Previous years' documents would have benefited a lot more from this. It's a great piece to keep at the ready I think. Thanks for delving into it.
