### ISSUE TITLE
Check Table 26

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#761]
Just quickly noting for now that the R0 values seem incorrect for at least the 2021 base model, perhaps other values are incorrect too.

**Comment by andrew-edwards** [comment]
Hadn't noticed this issue, but yes. I fixed the B0 problem, but R0 for 2020 disagrees with last year's reported median of 2,505. And exploitation fraction corresponding to SPR is 25.2% instead of 18.3%, and the 2021 value is 12.6% (exactly half of the value it shows for 2020). 
I thought it was an .rds issue but it isn't, Chris said he'd look into it.
