### ISSUE TITLE
Download new RDS file for the base model

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#766]
This will enable you to avoid running the build_model() again to get all the data for the MCMC -at-age tables. I haven't pushed the changes that use this yet (#763) but it won't hurt your current build if you get it now.

https://drive.google.com/file/d/1Q-UbHljIxhYQzLNBjGaO8Rt5c1Mp4t0_/view?usp=sharing

- [x] Chris
- [x] Andy
- [x] Kelli
- [x] Aaron

**Comment by cgrandin** [comment]
@aaron, the Dynamic B0 outputs are in there - 
`base.model$extra.mcmc$dynb*` objects:
```
base.model$extra.mcmc$dynb_fish
base.model$extra.mcmc$dynb_fish_median
base.model$extra.mcmc$dynb_nofish
base.model$extra.mcmc$dynb_nofish_median
```

The ones without `_median` have all the output from all iterations, so ~8000 rows per year and the `_median` ones have one row per year. The 'fish' ones are with fihing and the 'nofish' ones are without

**Comment by aaronmberger-nwfsc** [comment]
Great, thanks!

**Comment by andrew-edwards** [comment]
This breaks Figure A.4 (MCMC diagnostic histograms) because it uses `base.model$mcmcpath` which is set for Chris's computer. Rather than us change each path ourselves, Chris will fix the function later (as it's the only one that seems to break). This will enable us to share .rds files in the future without having to tweak anything.

**Comment by aaronmberger-nwfsc** [comment]
aha, good sleuthing Andy! - I couldn't figure that out before...
