### ISSUE TITLE
executive summary catches spacing of text is off

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#769]
The line spacing of the text in executive summary catches is smaller than the "stock" section that comes before it.

**Comment by andrew-edwards** [comment]
I noticed that. Will look into it. Will sort out some formatting issues later once we've finalised the text.

**Comment by cgrandin** [comment]
It happened when I merged those catch tables, and the `Table e` was changed automatically. I thought I was seeing things and then I forgot about it but yes there is an issue. It must be due to the `\Sexpr{}` values changing somehow in that section, because I changed those too.

See #708 and commit fa320f23e20a4a7da25ff62e7430634903ce44e2
