### ISSUE TITLE
Update the NUTS code in the appendix

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#809]
- [ ] update NUTS code in appendix.

**Comment by cgrandin** [comment]
Now I don't see the ADNUTS code in our 2021 doc. I swear I did see it before. I must have been looking at last year's. I gave second thought to this, we have the code as a function on the repo if anyone asks and we have never before included code for running the models, except for last year when we were in the process of changing over to ADNUTS.

**Comment by aaronmberger-nwfsc** [comment]
I also don't see any reason to do this and yes it was never in this years document because we don't have a NUTS sensitivity appendix anymore.  We don't add r4ss code.  We just did it last year b/c it was "new".  Plus, Cole said he's updating the code so that it will only be a few lines of code to run.

**Comment by kellijohnson-NOAA** [comment]
kk, closing b/c we don't need to do anything!
