### ISSUE TITLE
Management presentation - comments

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [pacific-hake/hake-assessment#818]
Nice job Andy - I think the management presentation will have more focus on it then in recent years given the trajectory of the stock and [already] comments on forecasting, etc.  Andy in the 🔦 ...  😄 

Slide 2: minor - could move the 2020 label to the right side of the box.
We may want to consider changing "JMC set adjusted TAC" to something different this year.  Maybe "Unilaterally summed TAC" - I think we used that once in the document.
It is interesting that the amount of difference between the dots and the squares in the figure is pretty consistent between 2017 - 2020.  Not sure that's worth mentioning verbally or not.

Slide 8: I think bullet j needs updating (probably b/c of my hard coding from a previous year)

I'll not make any comments on new historical probability analysis now b/c Andy is going to talk about those tomorrow.

**Comment by cgrandin** [comment]
Looks good Andy. Here's the couple things I found (**bold** is what I added/changed):

**Slide 4:**
Should be P(B**2022**/B0 < 0.4) = 17.8%
Should be P(relative fishing intensity at end of **2021** > 1.0) = 2.1%

**Slide 8:**
j. Median catch in **2021** is the same as fixed catch in **2022** (I just noticed in the decision table in the doc they are not exactly the same but they are supposed to be)

**Slide 15:**
The by-weight proportions were added because some stakeholders asked about them the year before when we just reported 'by numbers', I think it was so they could figure out how much of the catch was whatever cohort.

**Slide 19:**
Uncertainty is large, but **at the beginning of 2022** the stock has 17.8% chance of being below B40%, and 2.1% chance of
relative fishing intensity being above 100%

Slides 16-18 look great!

**Comment by andrew-edwards** [comment]
Thanks. Chris - you're Slide 4 and 19 comments are wrong though. These are talking about the current status, not projections. Yes?

**Comment by cgrandin** [comment]
The numbers in the slides match those in the risk tables for the next year, so without looking at code I assumed you meant those! My bad

**Comment by andrew-edwards** [comment]
Note to self:
- [ ] do above edits
- [ ] take Chris's slide of probabilities changing when using age-1 index
- [ ] move new slides to their own .pdf else people will look at them first without understanding them
- [ ] focus on 2019 point when introducing graph
- [ ] add \pause for the new bullets

**Comment by andrew-edwards** [comment]
Thanks for the suggestions. Just done them (agree with Aaron's suggestion of slightly moving the '20' in the first figure, but it's not a simple option in the code).

@cgrandin you said this:

"**Slide 15**
The by-weight proportions were added because some stakeholders asked about them the year before when we just reported 'by numbers', I think it was so they could figure out how much of the catch was whatever cohort."
 
Were you just explaining why the by-weight proportions were originally in there? I took them out because it was getting cluttered, but the by-weight figure is there and I'm pretty sure all the numbers are in the doc.

**Comment by andrew-edwards** [comment]
And I moved the new 'historical performance' slides into a new talk at: `beamer/SRG/Requests/historical-performance/`. Good idea (whoever suggested it, I forget!). Agree that we won't share it beforehand because it's easy to misunderstand the figures - we can let people know about it though so it's not a complete surprise that messes up the Agenda. 

And I put the caveats at the start to say these are preliminary ideas and feedback is welcome, including from JTC since we haven't had much time to discuss them. 

I did run some of it by an assessment colleague on the east coast and she liked it. Plus a stats PhD I'm working with at UBC who liked it, and agreed that the way to think of the events of 'biomass going down' or 'biomass below B40' is indeed as binary events (hence the 50% line), and it's a good sign that the assessment's don't give 0% or 100% prob of such things happening. 

But any questions are welcome from you guys in the meeting, especially if something doesn't make sense.

**Comment by andrew-edwards** [comment]
Made some more tweaks. In particular the one referenced above - I can't see that the 'default harvest rule catch' is a required assumption for the projected age composition of the catches (slide 15), since we only talk about proportions. Presumably these would be the same no matter what the catch is, yes?

**Comment by aaronmberger-nwfsc** [comment]
Moving the labels in that first figure used to be an option, but I see now that option is in the function management_catch_vs_tac_1_to_1 and we are now using management_catch_vs_tac_plot, so no worries.

**Comment by aaronmberger-nwfsc** [comment]
Comment on the historical performance slide: just a caution about the summary slide (14) first bullet in that we also only looked back to 2012 not before, and every since 2012 the stock has been pretty high so "correctly" projecting not to fall below B40% was probably not a big bar to meet.  I would imagine the correctness would not look so good during the low biomass period of say 2006-2012 when the biomass was actually bordering that binomial response variable (above/below B40%).  So maybe we just have to say these caveats or add in text that says stock was pretty high (well above B40%) from 2012 to current.

**Comment by cgrandin** [comment]
Re weight-at-age props.. I was asked by stakeholders one year what the actual values were by weight and I didn’t know. They were making a big deal of it for whatever reason so I added them for the following year. No big deal, you can leave them out but I just wanted to mention it

**Comment by andrew-edwards** [comment]
Added Aaron's 'not a high bar' comment, thanks. 4e6625f
