### ISSUE TITLE
Fig 16 and Fig on slide 5 of Assessment SRG Presentation

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#821]
This figure doesn't have the base model or the last model of the previous comparison to give any information in relative change of Update pre-2020 data to the model that came before it.

**Comment by aaronmberger-nwfsc** [comment]
Yes, this is a good idea.  I hadn't done it yet because there is essentially no difference between the end of bridge models 1 and the beginning of bridge models 2 (i.e., updating the pre-2020 data didn't do much at all.  And adding another line makes slide 5-6 legend overlap with the time series.  Let's consider this for the document, but I might just leave it for the presentation.

However! ... this comment did make me realize that my bridge model 1 was incorrect (was using mcmc=TRUE by default so had to fix that) - now I think flipping back and forth we can see during the meeting that the update to pre-2020 data makes near 0 difference.

**Comment by aaronmberger-nwfsc** [comment]
Upon further investigation there was a bit of change in some earlier spots of the time series (due to the rounding difference this year in some data) so I went ahead and changed the assessment presentation to address this as well as Figure 16 in the document.
