### ISSUE TITLE
SRG request recruitments in projection period

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#843]
# 2022 Assessment

SRG Request # 2

>The SRG recommends exploring alternative methods to simulate recruitment in the projections, such as drawing from past observations or using a mixture distribution, to characterize a different process than the assumed lognormal distribution.

## References

#812 also deals with this

**Comment by aaronmberger-nwfsc** [comment]
Best way to approach this is probably through ROMS informed recruitment drivers as a way to realize what future recruitment might be, rather than "+/- X" one-off methods.  (i.e., advocate for biologically based mechanisms to inform distributions of current/future recruitment)
@kellijohnson-NOAA is this correct?  Just making a note here to reference when drafting text in response to this request.

**Comment by kellijohnson-NOAA** [comment]
@kristinmarshall-NOAA tagging you here for the ROMS input

**Comment by aaronmberger-nwfsc** [comment]
I've added a blurb about this in our response to SRG requests.  It seems like this conversation relates to a new repo:  [pacific-hake/ss3roms](https://github.com/pacific-hake/ss3roms) so closing this issue as not much added info here.
