### ISSUE TITLE
hake_control std reporting

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#863]
Thanks to @rick-methot-NOAA for alerting me about the changes we should make in the std reporting section of the control file. Currently we are using option 1 which has specs for stdev selectivity, size, and numbers, where Rick is suggesting we use option 2 for additional output, which will lead to dynamic bzero and solve #857 and #858.

```
2 # (0/1/2) read specs for more stddev reporting: 0 = skip, 1 = read specs for reporting stdev for selectivity, size, and numbers, 2 = add options for M,Dyn. Bzero, SmryBio
 2 2 -1 4 # Selectivity: (1) 0 to skip or fleet, (2) 1=len/2=age/3=combined, (3) year, (4) N selex bins; NOTE: combined reports in age bins
 0 0 # Growth: (1) 0 to skip or growth pattern, (2) growth ages; NOTE: does each sex
 1 -1 1 # Numbers-at-age: (1) 0 or area(-1 for all), (2) year, (3) N ages;  NOTE: sums across morphs
 0 0 # Mortality: (1) 0 to skip or growth pattern, (2) N ages for mortality; NOTE: does each sex
2 # Dyn Bzero: 0 to skip, 1 to include, or 2 to add recr
0 # SmryBio: 0 to skip, 1 to include
 2 3 4 5 # vector with selex std bins (-1 in first bin to self-generate)
 # -1 # list of ages for growth std (-1 in first bin to self-generate)
 20 # vector with NatAge std ages (-1 in first bin to self-generate)
 # -1 # list of ages for NatM std (-1 in first bin to self-generate)
999
```

**Comment by Rick-Methot-NOAA** [comment]
Glad to help out. Sorry it took so long to finish up with the "report file
for each mceval" option. I learned more about controls for iostream along
the way.
I'll add my standard promo:  always a good idea to look at control.ss_new
to see the input format for new options that have been added.
Rick

**Comment by aaronmberger-nwfsc** [comment]
I think one of the changes in the report that I didn't catch had an unintended affect on our plot of survey selectivity posterior distribution.  Setting the following line in the stddev reporting section to have 4 age bins (because that is what is estimated for the survey):
2 2 -1 **4** # Selectivity: (1) 0 to skip or fleet, (2) 1=len/2=age/3=combined, (3) year, (4) N selex bins

creates the following:

![image](https://user-images.githubusercontent.com/7946234/150914580-bfe04ac7-e1e1-4228-b8eb-1ec1b9f738e7.png)

Instead of (from last year):

![image](https://user-images.githubusercontent.com/7946234/150914629-0f3a221e-9390-4735-bd63-b24e47e3de5d.png)

**Comment by cgrandin** [comment]
I fixed this plot to look like that because it just failed to plot. This is why I asked about the selectivity-at-age being truncated a week  ago (or so).

**Comment by aaronmberger-nwfsc** [comment]
The truncation still has all the information, it just doesn't look complete because it doesn't go to 0 at age-1 or 1 at max selectivity.

**Comment by andrew-edwards** [comment]
So the above fig is correct or it'll be revised (when I delete from cache)?

**Comment by cgrandin** [comment]
Yes, the truncated one is correct
