### ISSUE TITLE
Things that haven't changed (but presumably should have) with the corrected 2022 spawning biomass

### ISSUE THREAD

**Issue by andrew-edwards** [pacific-hake/hake-assessment#930]
Chris re-ran the base model with updated SS, that now gives B_2022 agreeing with the 'forecasted' B_2022 value. Fixes the issue with the one-page summary.

Chris posted hake-assessment-2022-feb-08-base-model-corrected.pdf.  [only the base model re-run]
I made feb-08-base-model-corrected-diff.pdf which shows the text [not figure] differences with the submitted preSRG version.

So B_2022 has changed, but projections correctly haven't changed because they were using the correct B_2022 etc. all along. 

However, I think some of these things should also have changed from the preSRG version but have not:
- [x] Table 18 (median biomass at age) for 2022.
- [x] Table 22 (biomass of large cohorts), should have changed for the final year for each cohort
- [x] Table 23 (medians of some things), some have correctly changed but age-2+ biomass should have also changed:
![image](https://user-images.githubusercontent.com/6977190/153091240-f38d8225-9cf2-4ae2-8eb4-02837d8f7e50.png)
- [x] Table 24 - same thing, just for credible intervals
- [x] Table 32-34 - relative spawning biomass for sens runs and retros now not comparable to base model. Chris says he can just do the mceval step for those.
- [x] Figure 16 and 17 - bridging models should have different B_2022 but hasn't changed. Presumably need to do mceval step again for those.

**Comment by cgrandin** [comment]
Basically need to run mceval for everything we’ve done. I’ll write a script to do it all in parallel on AWS machine

**Comment by andrew-edwards** [comment]
```
next.treaty.catch <- f(base.model$catch.levels[[catch.default.policy.ind]][[1]][1], 0)
```
still comes up as 716,264, instead of the updated 715,643 that comes from
```
catch.limit.quantiles <- f(as.numeric(quantile(base.model$mcmc[[paste0("ForeCatch_", end.yr)]],
                                               probs = c(0.025, 0.5, 0.975))))```  
```
- [ ] But I think the bigger issue is that catch streams m and n need redoing, yes? As they now disagree with the corrected one-page summary.

**Comment by cgrandin** [comment]
The default catch value changed a bit so we have to re run the whole catch levels calcs and forecasting. Sigh.

**Comment by cgrandin** [comment]
@andrew-edwards 
@kellijohnson-NOAA 
@aaronmberger-nwfsc 

It's finally done. The biomass trajectory is correct now as are the biomass numbers in the doc. The tables which remain unchecked above didn't change their 2022 values. My guess is SS doesn't output those values correctly, as they are coming straight from the SS output.

The default catch value is corrected as well, and all forecasts were re-run. See the decision table, it is now 715,643 in rows `m` and `n`.
Row `m` in `table h` should all be 1.00. I think it isn't quite because the tolerance wasn't high enough in the catch level determination routine. Could re-run that if we think it's necessary although I think it's close enough (at those high catch levels that won't be fished anyways).

To get all the updated RDS files, pull the repo and run the script `download_models_from_s3.R`. It will download and make small RDS's and will be way faster than trying to use the `s3_download("models", ext=rds")` method.

There's a copy of the doc on the Google Drive:
https://drive.google.com/file/d/1NkptX6615mJq6XBTtSbJgR0ZdC5iAP6m/view?usp=sharing

Andy here is the TEX file
[hake-assessment.tex.txt](https://github.com/pacific-hake/hake-assessment/files/8047133/hake-assessment.tex.txt)

**Comment by aaronmberger-nwfsc** [comment]
I pulled and don't see download_models_from_s3.R in the repo.
