### ISSUE TITLE
Running model with hess_step

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#965]
@cgrandin I am uncertain if this `if {} else {}` statement is working for both when `hess_step` is TRUE or FALSE. 

https://github.com/pacific-hake/hake-assessment/blob/926cc7df44772187f168f236bedcf4956b0ad645/R/run-adnuts.R#L122-L133 

I don't see why if you are doing the hessian that the executable is being ran in the model path and if you aren't then the executable is ran in the mcmc path. Can you please check the code because I don't know what `-hess_step 10 -binp ss.bar` is doing. But the original code in adnuts-run-base-model didn't use the mcmc_path it just ran everything in the model path so this line
https://github.com/pacific-hake/hake-assessment/blob/926cc7df44772187f168f236bedcf4956b0ad645/R/run-adnuts.R#L120
was enough.

Thanks!

**Comment by cgrandin** [comment]
Here's Cole's docs on `hess_step`, in his branch of the ADMB code :
https://github.com/Cole-Monnahan-NOAA/admb/blob/8888fe31722f68f251abdd5b2b2e58b043148d12/src/nh99/hmc_functions.cpp#L33

I think all it is supposed to do is improve the MLE, and give  much smaller maximum gradient. In theory this could give our MCMC run a better starting place, because the MLE is run with the `hess_step` feature inside the `mcmc` directory (all the models have an MLE run before the `MCMC` to get starting values, but this is supposed to be better). 

So I think the line inside `if(hess_step)` should be inside the `mcmc` directory:

`system_(paste0("cd ", mcmc_path, " && ", exe, " -hbf 1 -nox -iprint 200 -mcmc 15 -hess_step 10 -binp ss.bar"))`

Good catch...

**Comment by cgrandin** [comment]
I remember this was a pain because I had to switch to this commit and recompile ADMB AND SS just for this one test run, and try to keep track of the different compiles and which was being run for which model.

If I recall it didn't make any difference in the hake gradient/MLE estimated for the hake model anyway.
