### ISSUE TITLE
One-page summary average over past decade bullet 2

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hake-assessment#982]
https://github.com/pacific-hake/hake-assessment/blob/1a25c370250fde542114762118297cddcd139626/doc/one-page-summary/one-page-summary.rnw#L22-L24
says that 340,482 t is the average over the **past** decade but it is the average over the current year and the previous 9 years of total catches. I am not sure if we actually mean average over the latest 10 years or if we really should be calculating the average over the previous 10 years, i.e., not including this year?

**Comment by aaronmberger-nwfsc** [comment]
I saw that too and wondered the same thing. I ended up keeping it solely based on it being a legacy approach used by us in earlier assessments. In general though, I would think in a comparison like this that you would exclude the comparison year (2022) in the calculation of the recent decade (2012-2021).On Jan 18, 2023, at 2:55 PM, Kelli Johnson ***@***.***> wrote:﻿
Assigned #982 to @aaronmberger-nwfsc.

**Comment by andrew-edwards** [comment]
Good spot. Probably worth changing I would think. 

Presumably the ten-year average would be the same (almost) as we quoted last year. 

Maybe Table a should then have 11 years of catches, not 10 as it currently does?

**Comment by aaronmberger-nwfsc** [comment]
Because I like the 10 years in the table and the wording in the executive summary Catches section that says "Over the last 10 years,...", which then produces a number that now matches our one-page summary number of 340,482 t - I decided to leave the calculation in the one-page summary and instead change the wording around it. 
Previous it said: "...a 6% decrease from the average over the past decade of 340,482 t,..."
Changed to: "a 6\% decrease from the average over the most recent 10 years of 340,482 t,..."

That language now matches what we use in the executive summary and show in tables.  Good?  If not, feel free to re-open.

**Comment by andrew-edwards** [comment]
Don't think it quite addresses Kelli's original point though. That saying 2022 is a decrease from an average that includes 2022. Shouldn't it be a decrease from something that happened prior to 2022 (i.e. 2012-2021). 

I think it's okay to have a different number in exec-summary if it's clear we're talking about different things (and agree 10 years in the table is nice). Though we want the number in the one-page to also appear elsewhere, and too many numbers might be overkill.

Not quite sure of best solution. Maybe just keep calc as is and tweak wording to 
"... 6% below the average over the last ten years of 340,482 t,...  "
